### ISSUE TITLE
Avatar component can't render itself on server-side

### ISSUE THREAD

**Issue by KozaKrisz** [microsoft/fluentui#12547]
### Environment Information

- **Package version(s)**: 0.47.0
- **Browser and OS versions**: Microsoft Edge 80.0.361.109 

### Please provide a reproduction of the bug in a codepen:
I can't because I use the component on SSR Next.js

#### Actual behavior:

I try to use Avatar component on server-side with Next.js. I get an error with this message:

```shell
Cannot read property 'telemetry' of undefined
 at Avatar (C:\Dev\kozakrisz\node_modules\@fluentui\react-northstar\dist\commonjs\components\Avatar\Avatar.js:36:84)
    at processChild (C:\Dev\kozakrisz\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (C:\Dev\kozakrisz\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (C:\Dev\kozakrisz\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (C:\Dev\kozakrisz\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (C:\Dev\kozakrisz\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at render (C:\Dev\kozakrisz\node_modules\next\dist\next-server\server\render.js:82:16)
    at Object.renderPage (C:\Dev\kozakrisz\node_modules\next\dist\next-server\server\render.js:404:16)
    at Function.getInitialProps (C:\Dev\kozakrisz\.next\server\static\development\pages\_document.js:483:19)
    at Object.loadGetInitialProps (C:\Dev\kozakrisz\node_modules\next\dist\next-server\lib\utils.js:59:29)
    at Object.renderToHTML (C:\Dev\kozakrisz\node_modules\next\dist\next-server\server\render.js:408:36)
    at async DevServer.renderToHTMLWithComponents (C:\Dev\kozakrisz\node_modules\next\dist\next-server\server\next-server.js:634:26)
    at async DevServer.renderToHTML (C:\Dev\kozakrisz\node_modules\next\dist\next-server\server\next-server.js:774:28)
    at async DevServer.renderToHTML (C:\Dev\kozakrisz\node_modules\next\dist\server\next-dev-server.js:19:539)
    at async DevServer.render (C:\Dev\kozakrisz\node_modules\next\dist\next-server\server\next-server.js:513:22)
    at async Object.fn (C:\Dev\kozakrisz\node_modules\next\dist\next-server\server\next-server.js:371:17)
```

As I investigated the Avatar component can't create **context** , that should come from react-fela.

#### Expected behavior:

The component should render well.

### Priorities and help requested:

Are you willing to submit a PR to fix? no

Requested priority: Blocking

**Comment by jurokapsiar** [comment]
You need to use `Provider` component to inject the theme context. See https://fluentsite.z22.web.core.windows.net/components/provider/definition or the quick start guide: https://fluentsite.z22.web.core.windows.net/quick-start
