### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by jdhuntington** [microsoft/fluentui#13424]
Repro steps:

    $ git clone <repo>
    $ yarn
    $ yarn build

Expected: built repo

Actual:

```
@fluentui/ability-attributes: [11:32:40] Requiring external module @uifabric/build/babel/register
@fluentui/ability-attributes: internal/modules/cjs/loader.js:492
@fluentui/ability-attributes:   throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
@fluentui/ability-attributes:   ^
@fluentui/ability-attributes: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/jdh/projects/office-ui-fabric-react/node_modules/@babel/helper-compilation-targets/package.json
@fluentui/ability-attributes:     at applyExports (internal/modules/cjs/loader.js:492:9)
@fluentui/ability-attributes:     at resolveExports (internal/modules/cjs/loader.js:508:23)
@fluentui/ability-attributes:     at Function.Module._findPath (internal/modules/cjs/loader.js:632:31)
@fluentui/ability-attributes:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
@fluentui/ability-attributes:     at Function.Module._load (internal/modules/cjs/loader.js:884:27)
@fluentui/ability-attributes:     at Module.require (internal/modules/cjs/loader.js:1074:19)
@fluentui/ability-attributes:     at require (internal/modules/cjs/helpers.js:72:18)
@fluentui/ability-attributes:     at Object.<anonymous> (/Users/jdh/projects/office-ui-fabric-react/node_modules/@babel/preset-env/lib/debug.js:8:33)
@fluentui/ability-attributes:     at Module._compile (internal/modules/cjs/loader.js:1185:30)
@fluentui/ability-attributes:     at Module._compile (/Users/jdh/projects/office-ui-fabric-react/node_modules/pirates/lib/index.js:99:24) {
@fluentui/ability-attributes:   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
@fluentui/ability-attributes: }
@fluentui/ability-attributes: error Command failed with exit code 1.
@fluentui/ability-attributes: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jdhuntington** [comment]
This issue exists in:
- 12.17.0
- 14.x
- likely anything 13.x

`12.16.x` seems to be the last version that works

Might be fixable with a babel upgrade (https://github.com/nodejs/node/issues/32107)
