### ISSUE TITLE
Jest unable to render call to Fabric

### ISSUE THREAD

**Issue by reijam** [microsoft/fluentui#13694]
Latest version (7.120 )

Trying to invoke a test that creates a ContextMenu but jest chokes on the Fabric call in Layers because Layer renders in a separate rendering instance

```
      <span className="ms-layer" ref={this._rootRef}>
        {layerElement &&
          ReactDOM.createPortal(
            <Fabric {...(!eventBubblingEnabled && _getFilteredEvents())} className={classNames.content}>
              {this.props.children}
            </Fabric>,
            layerElement,
          )}
      </span>
```

The message starts out fairly innocently (as a warning) but proceeds downhill from there
```

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:120
      Warning: An invalid container has been provided. This may indicate that another renderer is being used in addition to the test renderer. (For example, ReactDOM.createPortal inside of a ReactTestRenderer tree.) This is not supported.
          in StyledFabricBase (created by LayerBase)
          in span (created by LayerBase)
          in LayerBase (created by Context.Consumer)
          in CustomizedLayer (created by Context.Consumer)
          in StyledCustomizedLayer (created by Callout)
          in Callout (created by ContextualMenuBase)
          in ContextualMenuBase (created by WithResponsiveMode)
          in WithResponsiveMode (created by Context.Consumer)
          in StyledWithResponsiveMode (at ColumnPicker.js:165)
          in ColumnPicker (at ColumnPicker.test.js:60)
    console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [TypeError: parentInstance.children.indexOf is not a function]
          at reportException (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
          at invokeEventListeners (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:209:9)
          at HTMLUnknownElementImpl._dispatch (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
          at Object.apply (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:10021:16)
          at invokeGuardedCallback (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:10073:31)
          at eventHandler (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:13001:9)
          at unstable_runWithPriority (C:\norepos\testmode\node_modules\scheduler\cjs\scheduler.development.js:653:12) TypeError: parentInstance.children.indexOf is not a function
          at appendChildToContainer (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:720:39)
          at insertOrAppendPlacementNodeIntoContainer (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:10960:7)
          at insertOrAppendPlacementNodeIntoContainer (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:10966:7)
          at insertOrAppendPlacementNodeIntoContainer (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:10966:7)
          at insertOrAppendPlacementNodeIntoContainer (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:10966:7)
          at commitPlacement (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:10944:5)
          at apply (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:13240:11)
          at HTMLUnknownElement.callCallback (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:9972:14)
          at invokeEventListeners (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:193:27)
          at HTMLUnknownElementImpl._dispatch (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (C:\norepos\testmode\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
          at Object.apply (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:10021:16)
          at invokeGuardedCallback (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:10073:31)
          at eventHandler (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:13001:9)
          at Scheduler_runWithPriority (C:\norepos\testmode\node_modules\scheduler\cjs\scheduler.development.js:653:12)
          at runWithPriority (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:1775:10)
          at commitRoot (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:12873:3)
          at finishSyncRender (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:12384:3)
          at callback (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:12370:7)
          at eventHandler (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:1825:24)
          at Scheduler_runWithPriority (C:\norepos\testmode\node_modules\scheduler\cjs\scheduler.development.js:653:12)
          at runWithPriority (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:1775:10)
          at flushSyncCallbackQueueImpl (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:1820:7)
          at flushSyncCallbackQueue (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:1808:3)
          at scheduleWork (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:11776:9)
          at updateContainer (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:14747:3)
          at create (C:\norepos\testmode\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:15455:5)
          at Object.<anonymous>.it (C:\norepos\testmode\src\__tests__\ColumnPicker.test.js:60:17)
          at Object.asyncJestTest (C:\norepos\testmode\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
          at resolve (C:\norepos\testmode\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
          at new Promise (<anonymous>)
          at mapper (C:\norepos\testmode\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
          at promise.then (C:\norepos\testmode\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
```
Tried searching for another instance of this issue ( I doubt I am the first to record it but i could not find any other incident reports )

If there is a workaround please advise

Thanks

**Comment by paulgildea** [comment]
@dzearing What's our support story for Portals?

**Comment by dzearing** [comment]
How are you testing? Are you using enzyme?

Just did a search on Jest React Portals and it seems like enzyme doesn't have an issue with portals. Curious if you've tried enzyme. See this:

https://stackoverflow.com/questions/48094581/testing-react-portals-with-enzyme

Also noticed in the callstack you're using react-test-renderer. Did a search for "react-test-renderer portals" and saw people mocking the portal API to get around the issue:

https://medium.com/@amanverma.dev/mocking-create-portal-to-utilize-react-test-renderer-in-writing-snapshot-uts-c49773c88acd

Have you tried that?

**Comment by dzearing** [comment]
@paulgildea This is more about how the test utilities work with things which use React portals. I don't think there is anything we would be able to do at the component layer to make testing easier here other than providing ways to override the behavior in particular environments in the case there's something blocking testing.

**Comment by reijam** [comment]
Cheers for the pointers. I have tested around this issue but these new pointers might be useful.

will keep you posted...
