### ISSUE TITLE
ScrollablePane precise scrolling bug

### ISSUE THREAD

**Issue by francescomazzella** [microsoft/fluentui#15157]
### Environment Information

- **Package version(s)**: 7.139
- **Browser and OS versions**: Edge (Chromium) 87.0.637.0

### Please provide a reproduction of the bug in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/7.138.0/#/examples/scrollablepane

#### Actual behavior:

Scrolling through the sections of the ScrollablePane, when a Sticky component intersects **precisely** another at the bottom, the page blanks out and the following error occurs:

`Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at pb (https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom.production.min.js:12:454)
    at n (https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom.production.min.js:13:221)
    at ya (https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom.production.min.js:153:221)
    at Object.enqueueSetState (https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom.production.min.js:202:409)
    at Sticky.t.setState (https://cdnjs.cloudflare.com/ajax/libs/react/16.8.6/umd/react.production.min.js:20:433)
    at Sticky._this._onScrollEvent (webpack:////mnt/work/3/s/packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx?:50:23)
    at eval (webpack:////mnt/work/3/s/packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.base.tsx?:73:21)
    at Set.forEach (<anonymous>)
    at ScrollablePaneBase._this.notifySubscribers (webpack:////mnt/work/3/s/packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.base.tsx?:71:36)
    at ScrollablePaneBase.componentDidUpdate (webpack:////mnt/work/3/s/packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.base.tsx?:329:18)`

The entire page also gets affected by this bug.

For this bug to be reproduced, pixel precision must be applied (for example with a precision touchpad).

#### Expected behavior:

The page shouldn't blank out, as the error shouldn't appear in the console.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: n/a

**Comment by paulgildea** [comment]
@francescomazzella Thanks for the issue.
