### ISSUE TITLE
TypeError: Cannot read property 'inCustomizerContext' of undefined

### ISSUE THREAD

**Issue by vipinnair22** [microsoft/fluentui#15943]
I'm trying to upgrade my codebase to the latest version of this package. But I'm getting the error mentioned in the title. I tried upgrading the enzyme adapter to the latest package as well. But it's not going away. 

```
at Object.useCustomizationSettings (../../node_modules/@uifabric/utilities/lib-commonjs/src/customizations/useCustomizationSettings.ts:12:11)
      at ../../node_modules/@uifabric/utilities/src/styled.tsx:93:22
      at renderWithHooks (../../node_modules/react-dom/cjs/react-dom.development.js:16260:18)
      at updateForwardRef (../../node_modules/react-dom/cjs/react-dom.development.js:18143:20)
      at beginWork$1 (../../node_modules/react-dom/cjs/react-dom.development.js:20211:16)
      at HTMLUnknownElement.callCallback (../../node_modules/react-dom/cjs/react-dom.development.js:336:14)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (../../node_modules/react-dom/cjs/react-dom.development.js:385:16)
      at invokeGuardedCallback (../../node_modules/react-dom/cjs/react-dom.development.js:440:31)
      at beginWork$$1 (../../node_modules/react-dom/cjs/react-dom.development.js:25780:7)
      at performUnitOfWork (../../node_modules/react-dom/cjs/react-dom.development.js:24698:12)
      at workLoopSync (../../node_modules/react-dom/cjs/react-dom.development.js:24671:22)
      at performSyncWorkOnRoot (../../node_modules/react-dom/cjs/react-dom.development.js:24270:11)
      at scheduleUpdateOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:23698:7)
      at updateContainer (../../node_modules/react-dom/cjs/react-dom.development.js:27103:3)
      at ../../node_modules/react-dom/cjs/react-dom.development.js:27528:7
      at unbatchedUpdates (../../node_modules/react-dom/cjs/react-dom.development.js:24433:12)
      at legacyRenderSubtreeIntoContainer (../../node_modules/react-dom/cjs/react-dom.development.js:27527:5)
      at Object.render (../../node_modules/react-dom/cjs/react-dom.development.js:27608:10)
      at render (../../node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:487:26)
      at fn (../../node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:404:37)
      at batchedUpdates$1 (../../node_modules/react-dom/cjs/react-dom.development.js:24386:12)
      at Object.act (../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1092:14)
      at act (../../node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:404:13)
      at Object.wrapAct [as render] (../../node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:473:16)
      at new render (../../node_modules/enzyme/src/ReactWrapper.js:115:16)
      at mount (../../node_modules/enzyme/src/mount.js:10:10)
```

It seems like it's unable to get this flag 

`var inCustomizerContext = customizations.inCustomizerContext;` in `useCustomizationSettings.js`

Is this a bug with the package or do I need to update any of the packages?
Thanks in advance!

**Comment by paulgildea** [comment]
@vipinnair22 Thanks for filing this issue. If you could provide a codepen or the package versions you are using to help us understand the root cause of this type issue.

@behowell Follow up once we have a starting point, I know we've been moving packages around lately, so it may be a regression. @khmakoto just FYI - not sure if this was part of the package restructure.

**Comment by vipinnair22** [comment]
@paulgildea 
Here are more details about the package versions and where the error is occuring.
```
"office-ui-fabric-react": "7.122.0",
"enzyme": "^3.11.0",
"enzyme-adapter-react-16": "^1.15.5",
"enzyme-to-json": "^3.6.1"
```

From the yarn.lock file

```
office-ui-fabric-react@7.122.0, office-ui-fabric-react@^7.117.0:
  version "7.122.0"
  resolved "https://registry.yarnpkg.com/office-ui-fabric-react/-/office-ui-fabric-react-7.122.0.tgz#b27956c6bb7c7513ccdfeb2f32df8002cc9179c2"
  integrity sha512-Gni7U5913e5dXKZRRVcZOcJgf6rsAENrcWGFboR8vvlwOcRbOz1UKivBZ9QkrHcs5rW4pt1INbD5QHIgLdQCkQ==
  dependencies:
    "@fluentui/date-time-utilities" "^7.1.3"
    "@fluentui/react-focus" "^7.12.19"
    "@fluentui/react-icons" "^0.1.36"
    "@microsoft/load-themed-styles" "^1.10.26"
    "@uifabric/foundation" "^7.7.35"
    "@uifabric/icons" "^7.3.61"
    "@uifabric/merge-styles" "^7.16.1"
    "@uifabric/react-hooks" "^7.5.0"
    "@uifabric/set-version" "^7.0.16"
    "@uifabric/styling" "^7.14.1"
    "@uifabric/utilities" "^7.24.1"
    prop-types "^15.7.2"
    tslib "^1.10.0"


"@uifabric/utilities@^7.24.1", "@uifabric/utilities@^7.28.0", "@uifabric/utilities@^7.33.2":
  version "7.33.2"
  resolved "https://registry.yarnpkg.com/@uifabric/utilities/-/utilities-7.33.2.tgz#426f9a8d1f9f7738e65abe4a9e36b65583476d81"
  integrity sha512-v2c3IUJdpru/hoGNOwIW549O5D4XBAc5sLpB7RREGI5ywoWuIJlNyYtBEGOwhAY62J2blj11qi86Ep+oZDM/Kw==
  dependencies:
    "@fluentui/dom-utilities" "^1.1.1"
    "@uifabric/merge-styles" "^7.19.1"
    "@uifabric/set-version" "^7.0.23"
    prop-types "^15.7.2"
    tslib "^1.10.0"

enzyme-adapter-react-16@^1.15.5:
  version "1.15.5"
  resolved "https://registry.yarnpkg.com/enzyme-adapter-react-16/-/enzyme-adapter-react-16-1.15.5.tgz#7a6f0093d3edd2f7025b36e7fbf290695473ee04"
  integrity sha512-33yUJGT1nHFQlbVI5qdo5Pfqvu/h4qPwi1o0a6ZZsjpiqq92a3HjynDhwd1IeED+Su60HDWV8mxJqkTnLYdGkw==
  dependencies:
    enzyme-adapter-utils "^1.13.1"
    enzyme-shallow-equal "^1.0.4"
    has "^1.0.3"
    object.assign "^4.1.0"
    object.values "^1.1.1"
    prop-types "^15.7.2"
    react-is "^16.13.1"
    react-test-renderer "^16.0.0-0"
    semver "^5.7.0"

enzyme-adapter-utils@^1.13.1:
  version "1.13.1"
  resolved "https://registry.yarnpkg.com/enzyme-adapter-utils/-/enzyme-adapter-utils-1.13.1.tgz#59c1b734b0927543e3d8dc477299ec957feb312d"
  integrity sha512-5A9MXXgmh/Tkvee3bL/9RCAAgleHqFnsurTYCbymecO4ohvtNO5zqIhHxV370t7nJAwaCfkgtffarKpC0GPt0g==
  dependencies:
    airbnb-prop-types "^2.16.0"
    function.prototype.name "^1.1.2"
    object.assign "^4.1.0"
    object.fromentries "^2.0.2"
    prop-types "^15.7.2"
    semver "^5.7.1"

enzyme-shallow-equal@^1.0.1, enzyme-shallow-equal@^1.0.4:
  version "1.0.4"
  resolved "https://registry.yarnpkg.com/enzyme-shallow-equal/-/enzyme-shallow-equal-1.0.4.tgz#b9256cb25a5f430f9bfe073a84808c1d74fced2e"
  integrity sha512-MttIwB8kKxypwHvRynuC3ahyNc+cFbR8mjVIltnmzQ0uKGqmsfO4bfBuLxb0beLNPhjblUEYvEbsg+VSygvF1Q==
  dependencies:
    has "^1.0.3"
    object-is "^1.1.2"

enzyme-shallow-until@^1.0.1:
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/enzyme-shallow-until/-/enzyme-shallow-until-1.0.1.tgz#37d07896b67820f849ec5e1de97145f0fe31dfb0"
  integrity sha512-2f+BbRmCBQPpydKT1T3UtZpRuF4OZWeXSIEeq5HyLzsIFSi01zhFxOM6OZurOYrvLF+ylL+TrXGSVA6qGKg2HQ==

enzyme-to-json@^3.6.1:
  version "3.6.1"
  resolved "https://registry.yarnpkg.com/enzyme-to-json/-/enzyme-to-json-3.6.1.tgz#d60740950bc7ca6384dfe6fe405494ec5df996bc"
  integrity sha512-15tXuONeq5ORoZjV/bUo2gbtZrN2IH+Z6DvL35QmZyKHgbY1ahn6wcnLd9Xv9OjiwbAXiiP8MRZwbZrCv1wYNg==
  dependencies:
    "@types/cheerio" "^0.22.22"
    lodash "^4.17.15"
    react-is "^16.12.0"

enzyme@^3.11.0:
  version "3.11.0"
  resolved "https://registry.yarnpkg.com/enzyme/-/enzyme-3.11.0.tgz#71d680c580fe9349f6f5ac6c775bc3e6b7a79c28"
  integrity sha512-Dw8/Gs4vRjxY6/6i9wU0V+utmQO9kvh9XLnz3LIudviOnVYDEe2ec+0k+NQoMamn1VrjKgCUOWj5jG/5M5M0Qw==
  dependencies:
    array.prototype.flat "^1.2.3"
    cheerio "^1.0.0-rc.3"
    enzyme-shallow-equal "^1.0.1"
    function.prototype.name "^1.1.2"
    has "^1.0.3"
    html-element-map "^1.2.0"
    is-boolean-object "^1.0.1"
    is-callable "^1.1.5"
    is-number-object "^1.0.4"
    is-regex "^1.0.5"
    is-string "^1.0.5"
    is-subset "^0.1.1"
    lodash.escape "^4.0.1"
    lodash.isequal "^4.5.0"
    object-inspect "^1.7.0"
    object-is "^1.0.2"
    object.assign "^4.1.0"
    object.entries "^1.1.1"
    object.values "^1.1.1"
    raf "^3.4.1"
    rst-selector-parser "^2.2.3"
    string.prototype.trim "^1.2.1"
```
From the call stack in the issue description I shared above, the error is occurring in `@uifabric/utilities` package in `@uifabric\utilities\lib-commonjs\customizations\useCustomizationSettings.js`. 

```
    var forceUpdate = useForceUpdate();
    var customizations = React.useContext(CustomizerContext_1.CustomizerContext).customizations;
    var inCustomizerContext = customizations.inCustomizerContext;
```

It seems like it's unable to get customizations from the `CustomizerContext`?

Previously we were using `@uifabric/utilities@^7.20.2` which didn't have this issue. I checked the code in that file. The logic has changed in the latest version of this package.

**Comment by vipinnair22** [comment]
Hi @paulgildea, @behowell, @jdhuntington,
Just wanted to follow up on this and check if you need more details on the issue :)

**Comment by behowell** [comment]
Hi @vipinnair22, are you able to provide a CodePen or [CodeSandbox](https://codesandbox.io/) to repro this issue? CodeSandbox might be a better option for this because it lets you set up a mini project and its dependencies.

cc @xugao, it looks like you were the last one to modify useCustomizationSettings.ts, do you know what might be causing this?

**Comment by xugao** [comment]
@vipinnair22 - the only reason I can think of for this to happen is when multiple versions of the utilities package are used. But based on your `yarn.lock` , it looks correct.

As @behowell mentioned, a repro will be helpful
