### ISSUE TITLE
Unit Test cases with Jest are failing while using office react ui fabric

### ISSUE THREAD

**Issue by TianyuHou** [microsoft/fluentui#16678]
Hi, we are using Office-UI-Fabric for our react project, it works fine in the past but when I upgraded react-scripts to v4.0.1, all the tests with ui-fabric failed and I was not able to figure it out. Could anyone please help?

Error message:
```
 FAIL  src/Test/Components/Common/UserNotification.test.tsx
  ● Test suite failed to run

    SyntaxError: C:\Users\tiho\OneDrive - Microsoft\Desktop\GetConnectedDev\CAC-FP-CCEIPE-GetConnected\GetConnected\GetConnectedUI\ClientApp\node_modules\office-ui-fabric-react\lib-commonjs\components\Stack\StackItem\StackItem.js: pragma and pragmaFrag cannot be set when runtime is automatic.
    > 1 | "use strict";
        | ^
      2 | Object.defineProperty(exports, "__esModule", { value: true });
      3 | /** @jsx withSlots */
      4 | var React = require("react");

      at File.buildCodeFrameError (node_modules/@babel/core/lib/transformation/file/file.js:250:12)
      at NodePath.buildCodeFrameError (node_modules/@babel/traverse/lib/path/index.js:138:21)
      at PluginPass.enter (node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:160:28)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:175:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:92:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:115:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:143:19)
```

Package.json:
```json
{
    "name": "test",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
        "@cseo/controls": "^1.10.1",
        "@cseo/styles": "^1.2.0",
        "@m365-admin/customizations": "^2.3.4",
        "@microsoft/applicationinsights-react-js": "^3.0.4",
        "@microsoft/applicationinsights-web": "^2.5.9",
        "@types/jest": "^26.0.20",
        "@types/lodash": "^4.14.167",
        "@types/moment-timezone": "^0.5.30",
        "@types/node": "^14.14.20",
        "@types/react": "^16.14.2",
        "@types/react-dom": "^16.9.10",
        "@types/react-router-dom": "^5.1.7",
        "@types/react-router-hash-link": "^1.2.1",
        "@uifabric/charting": "^2.8.1",
        "@uifabric/experiments": "^7.37.5",
        "@uifabric/react-cards": "^0.109.114",
        "axios": "^0.21.1",
        "core-js": "^3.8.2",
        "env-cmd": "^10.1.0",
        "history": "^4.10.1",
        "lodash": "^4.17.20",
        "mobx": "^5.15.7",
        "mobx-react": "^6.3.1",
        "moment": "^2.29.1",
        "moment-timezone": "0.5.31",
        "office-ui-fabric-core": "^11.0.0",
        "office-ui-fabric-react": "^7.155.3",
        "raf": "^3.4.1",
        "react": "^16.14.0",
        "react-adal": "^0.5.2",
        "react-device-detect": "^1.15.0",
        "react-dom": "^16.14.0",
        "react-router-dom": "^5.1.2",
        "react-router-hash-link": "^2.3.1",
        "react-scripts": "^4.0.1",
        "typescript": "3.9.5"
    },
    "scripts": {
        "start": "env-cmd -f .env.debug react-scripts start",
        "build": "react-scripts build",
        "build:PPE": "env-cmd -f .env.development npm run build",
        "build:PPE-east": "env-cmd -f .env.development-east npm run build",
        "build:Pre-Prod": "env-cmd -f .env.preproduction npm run build",
        "build:Prod": "env-cmd -f .env.production npm run build",
        "build:Prod-east": "env-cmd -f .env.production-east npm run build",
        "test": "react-scripts test src/Test/.*\\.test\\.[js,jsx,ts,tsx] --coverage --watchAll=false",
        "test:watch": "react-scripts test src/Test/.*\\.test\\.[js,jsx,ts,tsx] --coverage",
        "eject": "react-scripts eject",
        "lint": "eslint --ext .js,.ts,.tsx ./src",
        "lint-fix": "eslint --fix --ext .js,.ts,.tsx ./src"
    },
    "eslintConfig": {
        "extends": "react-app"
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "jest": {
        "collectCoverageFrom": [
            "src/Components/**/*.{js,jsx,ts,tsx}",
            "src/Helpers/**/*.{js,jsx,ts,tsx}",
            "!<rootDir>/node_modules/",
            "!<rootDir>/path/to/dir/"
        ],
        "transformIgnorePatterns": [
            "<rootDir>/node_modules/(?!(office-ui-fabric-react|@m365-admin|@uifabric)/)"
        ],
        "coverageThreshold": {
            "global": {
                "branches": 90,
                "functions": 90,
                "lines": 90,
                "statements": 90
            },
            "src/Components/**/*.{js,jsx,ts,tsx}": {
                "branches": 90,
                "functions": 90,
                "lines": 90,
                "statements": 90
            },
            "src/Helpers/**/*.{js,jsx,ts,tsx}": {
                "branches": 90,
                "functions": 90,
                "lines": 90,
                "statements": 90
            }
        },
        "coverageReporters": [
            "html",
            "cobertura",
            "json",
            "lcov",
            "text",
            "clover"
        ],
        "snapshotSerializers": [
            "enzyme-to-json/serializer"
        ]
    },
    "devDependencies": {
        "@types/enzyme": "^3.10.8",
        "@types/enzyme-adapter-react-16": "^1.0.6",
        "@types/react-adal": "^0.5.0",
        "@types/uuid": "^8.3.0",
        "@typescript-eslint/eslint-plugin": "^3.10.1",
        "enzyme": "^3.11.0",
        "enzyme-adapter-react-16": "^1.15.5",
        "enzyme-to-json": "^3.6.1",
        "eslint-plugin-typescript": "^0.14.0"
    }
}
```

tsConfig:
```json
{
  "compilerOptions": {
    "noFallthroughCasesInSwitch": true,
    "experimentalDecorators": true,
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "downlevelIteration": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}
```
}

**Comment by appsparkler** [comment]
+ 1

**Comment by ecraig12345** [comment]
This is because we have a few files which use `/** @jsx withSlots */` which conflicts with some changes to JSX handling in TS 4. You can find similar issues in many other front-end repos (search for "pragma and pragmaFrag cannot be set when runtime is automatic"), though from scanning through those it's not entirely clear if there's an easy solution.

In the meantime the easiest workaround might be to stay on react-scripts 3 if possible.

**Comment by appsparkler** [comment]
Hi @ecraig12345 ,

Thanks for your response!

Is it possible to include `/** @jsxRuntime classic */` on a line before the pragma?  I was able to get the test passing by adding it manually:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/12084821/106847753-8f1c5d00-66d5-11eb-8776-e4658337d029.png">


This is from the doc : [Customizing the Automatic Runtime Import](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx/#customizing-the-automatic-runtime-import)
<img width="762" alt="image" src="https://user-images.githubusercontent.com/12084821/106847944-f0dcc700-66d5-11eb-8f8f-ec6d1240d714.png">

**Comment by ecraig12345** [comment]
@appsparkler You mean in the Fluent UI React code? Unfortunately that appears to be a babel-specific pragma, and we compile with typescript.

**Comment by appsparkler** [comment]
@ecraig12345 ,  in the first screenshot; I made changes to the compiled `Stack.js` by adding the `/** jsxRuntime classic */`.  If you can include `/**jsxRuntime classic*/` in your source files, that should be enough IMO.

For example; in this file:
https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/components/Stack/StackItem/StackItem.tsx

```ts
/** @jsxRuntime classic */ // add this line
/** @jsx withSlots */
import * as React from 'react';
import { withSlots, createComponent, getSlots } from '@fluentui/foundation-legacy';
```

**Comment by ecraig12345** [comment]
I tried something similar in the [TS playground](https://www.typescriptlang.org/play?ts=3.7.5#code/PQKhAIAECsGcA8BKBXAdgFwJYFsCm4BjAGwENZZMDwRgAoUCGBcAMwHs3q6cAHNgJ3TVwZcIlwkCQlvzbZwAcn4SpCgNy0CbVLGkdwAXnAAKAHTmS-AOawAXCNQBPANoBdAJSGAfODQATXBZMVFw-DVpceD5BQm1dcABBHh57cUl0UwAxNClMbQBhOT4QjEMTTwMfAB4-TAA3YC8NIA) and it looks like having both pragmas works okay, including with TS 3.7.

**Comment by appsparkler** [comment]
Hi @ecraig12345, 

Any idea if the additional pragma will be added to source files?  

Thanks!

**Comment by ecraig12345** [comment]
Thanks for the PR @appsparkler! This problem still exists in some of the experimental components, but since those aren't officially supported I'm going to go ahead and close the issue. (If anyone needs the issue fixed for an experimental component, feel free to submit a PR similar to the other one #16863.)
