### ISSUE TITLE
yarn run test fails

### ISSUE THREAD

**Issue by joshualamusga1** [microsoft/fluentui#17321]
### Environment Information
- **Package version(s)**: master branch as of 3/8/21, 10:50am PST
- **Browser and OS versions**: Win10 64-bit

Initializing the Fluentui repo succeeds, builds, and performs change updates fine, but running tests fails.
Steps taken:
1. git clone https://github.com/microsoft/fluentui.git
2. yarn install
3. yarn run test

There are no changes to master yet when this occurs. Running `yarn run test` takes about 15 minutes before failing. The failure lists probably all packages in package.json, followed by:

```
ERR! ├─ abab@2.0.5
ERR! ├─ accepts@1.3.7
ERR! ├─ acorn-globals@6.0.0
```
... many lines between ...
```
ERR! ├─ xtend@4.0.2
ERR! ├─ yaml@1.10.0
ERR! ├─ yargs-parser@18.1.3
ERR! └─ yocto-queue@0.1.0
ERR! Initialized a git repository.
ERR!
ERR! Installing template dependencies using yarnpkg...
[1/4] Resolving packages...
[2/4] Fetching packages...
ERR! info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @fluentui/react@7.162.1" has incorrect peer dependency "@types/react@>=16.8.0 <17.0.0".
warning " > @fluentui/react@7.162.1" has incorrect peer dependency "@types/react-dom@>=16.8.0 <17.0.0".
warning " > @fluentui/react@7.162.1" has incorrect peer dependency "react@>=16.8.0 <17.0.0".
warning " > @fluentui/react@7.162.1" has incorrect peer dependency "react-dom@>=16.8.0 <17.0.0".
warning "@fluentui/react > office-ui-fabric-react@7.162.1" has incorrect peer dependency "@types/react@>=16.8.0 <17.0.0".
warning "@fluentui/react > office-ui-fabric-react@7.162.1" has incorrect peer dependency "@types/react-dom@>=16.8.0 <17.0.0".
warning "@fluentui/react > office-ui-fabric-react@7.162.1" has incorrect peer dependency "react@>=16.8.0 <17.0.0".
warning "@fluentui/react > office-ui-fabric-react@7.162.1" has incorrect peer dependency "react-dom@>=16.8.0 <17.0.0".
warning "@fluentui/react > office-ui-fabric-react > @fluentui/react-window-provider@1.0.2" has incorrect peer dependency "@types/react@>=16.8.0 <17.0.0".
```
... many lines between ...
```
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 35 new dependencies.
info Direct dependencies
ERR! ├─ @fluentui/cra-template@0.2.1
ERR! ├─ @fluentui/react@7.162.1
ERR! ├─ @testing-library/jest-dom@5.11.9
ERR! ├─ @testing-library/react@11.2.5
ERR! ├─ @testing-library/user-event@12.8.1
ERR! ├─ @types/jest@26.0.20
ERR! ├─ @types/node@12.20.4
ERR! ├─ @types/react-dom@17.0.1
ERR! ├─ @types/react@17.0.3
ERR! ├─ react-dom@17.0.1
ERR! ├─ react@17.0.1
ERR! ├─ typescript@4.2.3
ERR! └─ web-vitals@1.1.0
info All dependencies
ERR! ├─ @fluentui/cra-template@0.2.1
ERR! ├─ @fluentui/date-time-utilities@7.9.1
ERR! ├─ @fluentui/dom-utilities@1.1.2
ERR! ├─ @fluentui/keyboard-key@0.2.14
ERR! ├─ @fluentui/react-focus@7.17.5
ERR! ├─ @fluentui/react@7.162.1
ERR! ├─ @fluentui/theme@1.7.4
ERR! ├─ @testing-library/dom@7.30.0
ERR! ├─ @testing-library/jest-dom@5.11.9
ERR! ├─ @testing-library/react@11.2.5
ERR! ├─ @testing-library/user-event@12.8.1
ERR! ├─ @types/aria-query@4.2.1
ERR! ├─ @types/jest@26.0.20
ERR! ├─ @types/node@12.20.4
ERR! ├─ @types/prop-types@15.7.3
ERR! ├─ @types/react-dom@17.0.1
ERR! ├─ @types/react@17.0.3
ERR! ├─ @types/scheduler@0.16.1
ERR! ├─ @types/testing-library__jest-dom@5.9.5
ERR! ├─ @uifabric/foundation@7.9.25
ERR! ├─ @uifabric/icons@7.5.22
ERR! ├─ @uifabric/react-hooks@7.13.12
ERR! ├─ css.escape@1.5.1
ERR! ├─ css@3.0.0
ERR! ├─ csstype@3.0.7
ERR! ├─ dom-accessibility-api@0.5.4
ERR! ├─ lz-string@1.4.4
ERR! ├─ min-indent@1.0.1
ERR! ├─ office-ui-fabric-react@7.162.1
ERR! ├─ react-dom@17.0.1
ERR! ├─ react@17.0.1
ERR! ├─ redent@3.0.0
ERR! ├─ strip-indent@3.0.0
ERR! ├─ typescript@4.2.3
ERR! └─ web-vitals@1.1.0
ERR! We detected TypeScript in your project (src\App.test.tsx) and created a tsconfig.json file for you.
ERR! Your tsconfig.json has been populated with default values.
ERR!
ERR! Removing template package using yarnpkg...
ERR! 
[1/2] Removing module @fluentui/cra-template...
[2/2] Regenerating lockfile and installing missing dependencies...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
warning " > @fluentui/react@7.162.1" has incorrect peer dependency "@types/react@>=16.8.0 <17.0.0".
warning " > @fluentui/react@7.162.1" has incorrect peer dependency "@types/react-dom@>=16.8.0 <17.0.0".
```
... many lines between ...
```
warning "@fluentui/react > office-ui-fabric-react > @uifabric/styling > @fluentui/theme@1.7.4" has incorrect peer dependency "react@>=16.8.0 <17.0.0".
warning "@fluentui/react > office-ui-fabric-react > @uifabric/styling > @fluentui/theme@1.7.4" has incorrect peer dependency "react-dom@>=16.8.0 <17.0.0".
warning " > @testing-library/user-event@12.8.1" has unmet peer dependency "@testing-library/dom@>=7.21.4".
success Uninstalled packages.
ERR!
ERR! Created git commit.
ERR!
ERR! Success! Created cra-app at C:\Users\user\AppData\Local\Temp\cra-test-29704LzGc27epJ78Z\cra-app
ERR! Inside that directory, you can run several commands:
ERR! 
ERR!   yarn start
ERR!     Starts the development server.
ERR!
ERR!   yarn build
ERR!     Bundles the app into static files for production.
ERR!
ERR!   yarn test
ERR!     Starts the test runner.
ERR! 
ERR!   yarn eject
ERR!     Removes this tool and copies build dependencies, configuration files
ERR!     and scripts into the app directory. If you do this, you can’t go back!
ERR!
ERR! We suggest that you begin by typing:
ERR!
ERR!   cd C:\Users\user\AppData\Local\Temp\cra-test-29704LzGc27epJ78Z\cra-app
ERR!   yarn start
ERR! 
ERR! Happy hacking!
ERR! + cd C:\Users\user\AppData\Local\Temp\cra-test-29704LzGc27epJ78Z\cra-app && CI=true yarn build
ERR! @fluentui/cra-template: tests failed with error:
ERR! Error: child process exited with code 1
ERR!     at ChildProcess.<anonymous> (C:\s\f\fluentui\scripts\gulp\/sh.ts:29:14)
ERR!     at ChildProcess.emit (events.js:310:20)
ERR!     at maybeClose (internal/child_process.js:1021:16)
ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
ERR! 'CI' is not recognized as an internal or external command,
ERR! operable program or batch file.
ERR!  ELIFECYCLE
ERR! npm ERR! errno 1
ERR! npm ERR! @fluentui/cra-template@0.2.1 test: `node -r @fluentui/scripts/babel/register scripts/test.ts`
ERR! npm ERR! Exit status 1
ERR! npm ERR!
ERR! npm ERR! Failed at the @fluentui/cra-template@0.2.1 test script.
ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ERR!
ERR! npm ERR! A complete log of this run can be found in:
ERR! npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-03-08T18_52_27_136Z-debug.log
ERR! failed
info ----------------------------------------------
info Took a total of 18m 16.12s to complete
error Command failed with exit code 1.
```

I'm looking for any hints as to why running tests fails with errors related to create-react-app. (It would also be nice to run tests on a specific file under packages/react, though it's unclear how to do that, and changing to the packages/react directory to run tests has its own errors, so I'd rather solve the main issue first.)

**Comment by ecraig12345** [comment]
It looks like the failure is in the cra-template tests which @kubkon recently worked on.

**Comment by ecraig12345** [comment]
Looking at this again, the issue is likely that you didn't build before running tests (this is required at the moment). The following should work; if not, please file a new issue with details.
```
yarn
yarn build
yarn test
```
(If you only want to run tests up to a certain project, you can add `--to project-name` to the build and test commands above.)
