### ISSUE TITLE
Uncaught exception (might) with Combobox

### ISSUE THREAD

**Issue by Kingwl** [microsoft/fluentui#17704]
### Environment Information

- **Package version(s)**: (fill this out) 7.117.0 
- **Browser and OS versions**: (fill this out if relevant) Windows Chrome

#### Actual behavior:

An exception throws. It's might caused by some kind of race condition of context initialize.

exception stack:

```
TypeError: Cannot read property 'semanticColors' of undefined
at semanticColors (../../src/components/ComboBox/ComboBox.styles.ts:261:12)
at  (../../src/memoize.ts:130:28)
at getStyles (../../src/components/ComboBox/ComboBox.tsx:399:10)
at render (../../../node_modules/react-dom/cjs/react-dom.production.min.js:181:191)
at vi (../../../node_modules/react-dom/cjs/react-dom.production.min.js:180:281)
at ui (../../../node_modules/react-dom/cjs/react-dom.production.min.js:261:395)
at gk (../../../node_modules/react-dom/cjs/react-dom.production.min.js:230:21)
at fk (../../../node_modules/react-dom/cjs/react-dom.production.min.js:229:361)
at Zj (../../../node_modules/react-dom/cjs/react-dom.production.min.js:223:215)
at c (../../../node_modules/react-dom/cjs/react-dom.production.min.js:121:114)
```

#### Expected behavior:

No exceptions.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by tomi-msft** [comment]
Hi @Kingwl, thanks for submitting the issue. Could you provide a codepen with the problem repro'd so that I can investigate a bit more? Thanks!

**Comment by Kingwl** [comment]
Sorry for the delay.

Actually, it's reported by telemetry. And I cannot repro this on as an MVP. 

Does the team have seen this before? If not, It's okay to close this.
