### ISSUE TITLE
Prop `className` did not match.

### ISSUE THREAD

**Issue by akaila** [microsoft/fluentui#17751]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^8.5.0"
- **Browser and OS versions**: macOS Big Sur

### Please provide a reproduction of the bug in a codepen:

Using server rendering in next.js for the following snippet

```
         <div className="ms-Grid-col ms-hiddenLgUp">
            <IconButton
              iconProps={{ iconName: "GlobalNavButton" }}
              menuProps={{
                isBeakVisible: false,
                items: [],
              }}
              menuIconProps={{ style: { display: "hidden" }, iconName: "" }}
            />
          </div>
```

#### Actual behavior:

Console.log emits the warning:

```
Warning: Prop `className` did not match. Server: "ms-Icon server-root-37 server-css-8 ms-Button-icon server-icon-3" Client: "ms-Icon root-37 css-61 ms-Button-icon icon-56"
    at i
    at FontIcon (webpack-internal:///./node_modules/@fluentui/react/lib/components/Icon/FontIcon.js:36:26)
    at span
    at button
    at BaseButton (webpack-internal:///./node_modules/@fluentui/react/lib/components/Button/BaseButton.js:32:28)
    at IconButton (webpack-internal:///./node_modules/@fluentui/react/lib/components/Button/IconButton/IconButton.js:20:42)
    at CustomizedIconButton (webpack-internal:///./node_modules/@fluentui/utilities/lib/customizations/customizable.js:23:40)
    at div
    at div
    at div
    at div
    at NavigationBar
    at div
    at div
```

#### Expected behavior:

No warning should be emitted and classnames should match during hydration.

Requested priority: (Blocking, High, Normal, Low) Normal

**Comment by akaila** [comment]
I noticed that server-root-37 does not exist in client CSS.

**Comment by tomi-msft** [comment]
Hi @akaila, thanks for submitting the issue. I am having trouble reproing this, would you mind submitting a codepen that successfully repros this, so I can assist further?
