### ISSUE TITLE
@fluentui/make-styles: throws in SSR

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#17890]
### Environment Information

- **Package version(s)**: @fluentui/make-styles@9.0.0-alpha.12
- **Browser and OS versions**: NA

#### Actual behavior:

```tsx
ReferenceError: document is not defined
    at Object.createDOMRenderer (C:\Users\olfedias\WebstormProjects\fluentui-ssr\node_modules\@fluentui\make-styles\lib-commonjs\renderer\createDOMRenderer.js:55:30)
    at C:\Users\olfedias\WebstormProjects\fluentui-ssr\node_modules\@fluentui\react-make-styles\lib-commonjs\useRenderer.js:7:30
    at Object.useMemo (C:\Users\olfedias\WebstormProjects\fluentui-ssr\node_modules\react-dom\cjs\react-dom-server.node.development.js:1582:19)
    at Object.useMemo (C:\Users\olfedias\WebstormProjects\fluentui-ssr\node_modules\react\cjs\react.development.js:1532:21)
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
Requested priority: Normal
Products/sites affected: (if applicable)

**Comment by layershifter** [comment]
Duplicate of #17902.
