### ISSUE TITLE
Cannot read property '__events__' of undefined

### ISSUE THREAD

**Issue by martinchrzan** [microsoft/fluentui#18493]
Hi, I am trying to test my react components using jest + react-test-renderer

my test contains only this:

`const component = renderer.create(<ComponentContainingDialog />)`

However it throws an error when my component contais <Dialog> control

```
TypeError: Cannot read property '__events__' of undefined

      at EventGroup.on (node_modules/@fluentui/utilities/src/EventGroup.ts:194:69)
      at WithResponsiveMode.componentDidMount (node_modules/@fluentui/react/lib-commonjs/utilities/src/utilities/decorators/withResponsiveMode.tsx:95:20)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11782:24)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14172:9)
      at unstable_runWithPriority (node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2486:10)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14011:3)

```

This is being thrown from <Modal> and <WithResponsiveMode> components

Any solution how to prevent this? 

### Environment Information

- **Package version(s)**: 8.14.2
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

running jest test should not throw an error

#### Expected behavior:

throws an error

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
You'll need to add a mock like this:
```tsx
const createNodeMock = (el: React.ReactElement<{}>) => {
  return {
    __events__: {},
    addEventListener: () => undefined,
    removeEventListener: () => undefined,
  };
};

const component = renderer.create(<ComponentContainingDialog />, { createNodeMock });
```
