### ISSUE TITLE
Cannot read property 'isBlocking' of undefined

### ISSUE THREAD

**Issue by wamoha** [microsoft/fluentui#19069]
### Environment Information

- **Package version(s)**: 8.13.1
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

We are seeing the below error intermittently in our production systems. We have been noticing runtime errors in components where the props is undefined during componentDidUpdate event. We did raise this [issue ](https://github.com/microsoft/fluentui/issues/18084)before here but haven't got much traction.

#https://github.com/microsoft/fluentui/issues/18084

#### Actual behavior:

`TypeError: Cannot read property 'isBlocking' of undefined
    at isBlocking (../../src/components/Panel/Panel.base.tsx:319:19)
    at _shouldListenForOuterClick (../../src/components/Panel/Panel.base.tsx:122:50)
    at ../../src/appendFunction.ts:13:48
    at forEach (../../src/appendFunction.ts:13:14)
    at componentDidUpdate (../../../node_modules/react-dom/cjs/react-dom.production.min.js:219:501)
    at Yi (../../../node_modules/react-dom/cjs/react-dom.production.min.js:259:159)
    at b (../../../node_modules/scheduler/cjs/scheduler.production.min.js:18:342)
    at Nf (../../../node_modules/react-dom/cjs/react-dom.production.min.js:122:324)
    at gg (../../../node_modules/react-dom/cjs/react-dom.production.min.js:252:278)`

#### Expected behavior:

Runtime error should not be thrown

### Priorities and help requested:

Are you willing to submit a PR to fix?  #No

Requested priority: High

Products/sites affected: ml.azure.com

**Comment by ling1726** [comment]
@wamoha, I understand that this is similar to #18084, but unfortunately we really do need some repro steps to be able to investigate further.  `this.props` should generally not be defined in a React component. For this particular problem we could 'solve' this by checking `this.props` but would make sense to do so without knowing why.

Looking at the stack trace, are you possibly using `appendFunction` in any way ? perhaps through `extendComponent` ?

Even some more context into how you are using the Panel component would help
