### ISSUE TITLE
TypeError: Cannot read property 'inCustomizerContext' of undefined when mounting ShimmeredDetailsList

### ISSUE THREAD

**Issue by ginnif** [microsoft/fluentui#19354]
I'm creating jest test for the component ShimmeredDetailsList. When I used mount(ShimmeredDetailsList items={[]} />, it will throw me the TypeError: Cannot read property 'inCustomizerContext' of undefined. However if I changed to `mount(<PrimaryButton />`, the console did not throw any error. So is there something wrong with the ShimmeredDetailsList component? 
I tried to downgrade and upgrade uifabric, office-ui-fabric-react and enzyme but didn't work. 

For this console error:   at Object.useCustomizationSettings (node_modules/@uifabric/utilities/lib-commonjs/src/customizations/useCustomizationSettings.ts:12:11)  I don't even find the src folder under commonjs, the customizations folder is just under commonjs

```
  at Object.useCustomizationSettings (node_modules/@uifabric/utilities/lib-commonjs/src/customizations/useCustomizationSettings.ts:12:11)
      at node_modules/@uifabric/utilities/src/styled.tsx:93:22
      at Component (node_modules/react-dom/cjs/react-dom.development.js:14825:18)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16840:20)
      at updateForwardRef (node_modules/react-dom/cjs/react-dom.development.js:18678:16)
      at HTMLUnknownElement.apply (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.dispatchEvent (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at apply (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:23234:7)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:22188:12)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22161:22)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:21787:9)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21219:7)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:24407:3)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24792:7)
      at fn (node_modules/react-dom/cjs/react-dom.development.js:21934:12)
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:24791:5)
      at Object.legacyRenderSubtreeIntoContainer [as render] (node_modules/react-dom/cjs/react-dom.development.js:24874:10)
      at ReactDOM (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:488:17)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:37)
      at fn (node_modules/react-dom/cjs/react-dom.development.js:21887:12)
      at Object.batchedUpdates [as act] (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at TestUtils (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:405:3)
      at Object.wrapAct [as render] (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:474:16)
      at new renderer (node_modules/enzyme/src/ReactWrapper.js:115:7)
      at Object.mount (node_modules/enzyme/src/mount.js:10:10)
```

**Comment by ginnif** [comment]
@smhigley  Could you please help on this issue?

**Comment by gouttierre** [comment]
@gingi - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [Shimmer ](https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/shimmer) examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
