### ISSUE TITLE
Storybook broken for converged packages

### ISSUE THREAD

**Issue by andrefcdias** [microsoft/fluentui#19662]
### Please provide a reproduction:

- Clone repo on `master`
- Install dependencies
- Run `yarn start` / `yarn workspace @fluentui/react-button start`
- Pick `@fluentui/react-button`

#### Actual behavior:

Error is thrown and Storybook does not start. This seems to be happening for component packages only (tested Button and Card) as `react-components` starts with no issues.

```
ERROR in ./.storybook/storybook-init-framework-entry.js
Module build failed (from /home/afcdias/workspace/fluentui-master/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/home/afcdias/workspace/fluentui-master/node_modules/@fluentui/babel-make-styles/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at resolve (internal/modules/cjs/helpers.js:94:19)
    at resolveStandardizedName (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/files/plugins.js:111:7)
    at resolvePlugin (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/files/plugins.js:55:10)
    at loadPlugin (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/files/plugins.js:63:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/config-descriptors.js:187:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:291:5)
    at /home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:43:15)
    at Function.all (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:216:13)
 @ multi /home/afcdias/workspace/fluentui-master/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js /home/afcdias/workspace/fluentui-master/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[2]

ERROR in ./.storybook/preview.js-generated-config-entry.js
Module build failed (from /home/afcdias/workspace/fluentui-master/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/home/afcdias/workspace/fluentui-master/node_modules/@fluentui/babel-make-styles/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at resolve (internal/modules/cjs/helpers.js:94:19)
    at resolveStandardizedName (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/files/plugins.js:111:7)
    at resolvePlugin (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/files/plugins.js:55:10)
    at loadPlugin (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/files/plugins.js:63:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/config-descriptors.js:187:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:291:5)
    at /home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:43:15)
    at Function.all (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:216:13)
 @ multi /home/afcdias/workspace/fluentui-master/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js /home/afcdias/workspace/fluentui-master/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[14]

ERROR in ./.storybook/generated-stories-entry.js
Module build failed (from /home/afcdias/workspace/fluentui-master/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/home/afcdias/workspace/fluentui-master/node_modules/@fluentui/babel-make-styles/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at resolve (internal/modules/cjs/helpers.js:94:19)
    at resolveStandardizedName (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/files/plugins.js:111:7)
    at resolvePlugin (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/files/plugins.js:55:10)
    at loadPlugin (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/files/plugins.js:63:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/home/afcdias/workspace/fluentui-master/node_modules/@babel/core/lib/config/config-descriptors.js:187:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:291:5)
    at /home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:43:15)
    at Function.all (/home/afcdias/workspace/fluentui-master/node_modules/gensync/index.js:216:13)
 @ multi /home/afcdias/workspace/fluentui-master/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js /home/afcdias/workspace/fluentui-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js /home/afcdias/workspace/fluentui-master/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[15]
```

#### Expected behavior:

Storybook gets started

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: Inner loop development

**Comment by tringakrasniqi** [comment]
Maybe worth noting: the react-components storybook works and does not result in this error, `yarn workspace @fluentui/react-components start`.

**Comment by micahgodbolt** [comment]
Ran into this myself, and resolved it by building make-styles, and then building babel-make-styles, then I was able to successfully run a single component storybook
