### ISSUE TITLE
Investigate rollup projects-test error

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#20220]
We've intermittently been getting this failure in `test:projects:rollup` about a couple times per week in CI.

Example: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=222640&view=results

```
verb @fluentui/projects-test test |  ================================================================================
verb @fluentui/projects-test test |  test:projects:rollup : ✔️ Used lerna config: /mnt/vss/_work/1/s/packages/fluentui/lerna.json
verb @fluentui/projects-test test |  ================================================================================
verb @fluentui/projects-test test |  TypeError: Cannot read property 'localDependencies' of undefined
verb @fluentui/projects-test test |      at forEach (/mnt/vss/_work/1/s/scripts/projects-test/packPackages.ts:18:29)
verb @fluentui/projects-test test |      at Array.forEach (<anonymous>)
verb @fluentui/projects-test test |      at flattenPackageGraph (/mnt/vss/_work/1/s/scripts/projects-test/packPackages.ts:15:16)
verb @fluentui/projects-test test |      at packProjectPackages (/mnt/vss/_work/1/s/scripts/projects-test/packPackages.ts:56:28)
verb @fluentui/projects-test test |      at rollup (/mnt/vss/_work/1/s/packages/fluentui/projects-test/src/rollup.ts:36:26)
verb @fluentui/projects-test test |      at performTest (/mnt/vss/_work/1/s/packages/fluentui/projects-test/src/index.ts:10:5)
verb @fluentui/projects-test test |  
```

**Comment by ecraig12345** [comment]
oops, same as #20483
