### ISSUE TITLE
tabster: errors in react-popover tests after bumping to jest26 (JSDOM 16)

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#20883]
After migrating to jest 26 (that uses JSDOM 16), following runtime errors are being triggered. It is not causing test to fail, but this should be addressed to not spam log files to much/mitigate potential memory leaks/having non deterministic tests.

#### Repro:

- checkout https://github.com/microsoft/fluentui/pull/20716
- run `yarn` to install new deps
- run `yarn workspace @fluentui/react-popover`

**Errors logged**
 
```
 console.error
      Modalizer element must have aria-label <ref *1> HTMLDivElement {
        '__reactInternalInstance$7nj57x1xmzb': <ref *2> FiberNode {
          tag: 5,
          key: null,
          elementType: 'div',
          type: 'div',
          stateNode: [Circular *1],
          return: FiberNode {
            tag: 4,
            key: null,
            elementType: null,
            type: null,
            stateNode: [Object],
            return: [FiberNode],
            child: [Circular *2],
            sibling: null,
            index: 0,
            ref: null,
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: null,
            memoizedState: null,
            contextDependencies: null,
            mode: 0,
            effectTag: 0,
            nextEffect: null,
            firstEffect: [FiberNode],
            lastEffect: [Circular *2],
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: null,
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 166,
            _debugSource: null,
            _debugOwner: null,
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: null
          },
          child: FiberNode {
            tag: 5,
            key: null,
            elementType: 'div',
            type: 'div',
            stateNode: [HTMLDivElement],
            return: [Circular *2],
            child: null,
            sibling: [FiberNode],
            index: 0,
            ref: [Object],
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: null,
            memoizedState: null,
            contextDependencies: null,
            mode: 0,
            effectTag: 128,
            nextEffect: [Circular *2],
            firstEffect: null,
            lastEffect: null,
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: null,
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 168,
            _debugSource: null,
            _debugOwner: [FiberNode],
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: null
          },
          sibling: null,
          index: 0,
          ref: [Function (anonymous)] { current: [Circular *1] },
          pendingProps: {
            role: 'dialog',
            'data-tabster': '{"deloser":{},"modalizer":{"id":"modal-1","isOthersAccessible":true}}',
            'data-testid': 'component',
            onMouseLeave: [Function (anonymous)],
            children: [Array],
            onMouseEnter: [Function (anonymous)],
            onKeyDown: [Function (anonymous)],
            className: 'fui-PopoverSurface ___1vg5ewp fxugw4r f1hg901r fff7au0 f1bjk9e1 fwsfkhu f8wkphi f5ogflp f1hqa2wf f1f09k3d finvdd3 fzkkow9 fcdblym fg706s2 fjik90z fghlq4f f1gn591s fb073pr fjscplz fqag9an f1gbmcue fp67ikv f1rh9g5y'
          },
          memoizedProps: {
            role: 'dialog',
            'data-tabster': '{"deloser":{},"modalizer":{"id":"modal-1","isOthersAccessible":true}}',
            'data-testid': 'component',
            onMouseLeave: [Function (anonymous)],
            children: [Array],
            onMouseEnter: [Function (anonymous)],
            onKeyDown: [Function (anonymous)],
            className: 'fui-PopoverSurface ___1vg5ewp fxugw4r f1hg901r fff7au0 f1bjk9e1 fwsfkhu f8wkphi f5ogflp f1hqa2wf f1f09k3d finvdd3 fzkkow9 fcdblym fg706s2 fjik90z fghlq4f f1gn591s fb073pr fjscplz fqag9an f1gbmcue fp67ikv f1rh9g5y'
          },
          updateQueue: null,
          memoizedState: null,
          contextDependencies: null,
          mode: 0,
          effectTag: 128,
          nextEffect: FiberNode {
            tag: 5,
            key: null,
            elementType: 'span',
            type: 'span',
            stateNode: [HTMLSpanElement],
            return: [FiberNode],
            child: [FiberNode],
            sibling: null,
            index: 0,
            ref: [Object],
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: null,
            memoizedState: null,
            contextDependencies: null,
            mode: 0,
            effectTag: 128,
            nextEffect: [FiberNode],
            firstEffect: [FiberNode],
            lastEffect: [Circular *2],
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: null,
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 165,
            _debugSource: null,
            _debugOwner: [FiberNode],
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: null
          },
          firstEffect: FiberNode {
            tag: 5,
            key: null,
            elementType: 'div',
            type: 'div',
            stateNode: [HTMLDivElement],
            return: [Circular *2],
            child: null,
            sibling: [FiberNode],
            index: 0,
            ref: [Object],
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: null,
            memoizedState: null,
            contextDependencies: null,
            mode: 0,
            effectTag: 128,
            nextEffect: [Circular *2],
            firstEffect: null,
            lastEffect: null,
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: null,
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 168,
            _debugSource: null,
            _debugOwner: [FiberNode],
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: null
          },
          lastEffect: FiberNode {
            tag: 5,
            key: null,
            elementType: 'div',
            type: 'div',
            stateNode: [HTMLDivElement],
            return: [Circular *2],
            child: null,
            sibling: [FiberNode],
            index: 0,
            ref: [Object],
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: null,
            memoizedState: null,
            contextDependencies: null,
            mode: 0,
            effectTag: 128,
            nextEffect: [Circular *2],
            firstEffect: null,
            lastEffect: null,
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: null,
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 168,
            _debugSource: null,
            _debugOwner: [FiberNode],
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: null
          },
          expirationTime: 0,
          childExpirationTime: 0,
          alternate: null,
          actualDuration: 0,
          actualStartTime: -1,
          selfBaseDuration: 0,
          treeBaseDuration: 0,
          _debugID: 167,
          _debugSource: null,
          _debugOwner: FiberNode {
            tag: 11,
            key: null,
            elementType: [Object],
            type: [Object],
            stateNode: null,
            return: [FiberNode],
            child: [FiberNode],
            sibling: null,
            index: 0,
            ref: null,
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: [Object],
            memoizedState: [Object],
            contextDependencies: [Object],
            mode: 0,
            effectTag: 517,
            nextEffect: [FiberNode],
            firstEffect: [FiberNode],
            lastEffect: [FiberNode],
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: null,
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 163,
            _debugSource: null,
            _debugOwner: null,
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: [Array]
          },
          _debugIsCurrentlyTiming: false,
          _debugHookTypes: null
        },
        '__reactEventHandlers$7nj57x1xmzb': {
          role: 'dialog',
          'data-tabster': '{"deloser":{},"modalizer":{"id":"modal-1","isOthersAccessible":true}}',
          'data-testid': 'component',
          onMouseLeave: [Function (anonymous)],
          children: [ [Object], 'Content' ],
          onMouseEnter: [Function (anonymous)],
          onKeyDown: [Function (anonymous)],
          className: 'fui-PopoverSurface ___1vg5ewp fxugw4r f1hg901r fff7au0 f1bjk9e1 fwsfkhu f8wkphi f5ogflp f1hqa2wf f1f09k3d finvdd3 fzkkow9 fcdblym fg706s2 fjik90z fghlq4f f1gn591s fb073pr fjscplz fqag9an f1gbmcue fp67ikv f1rh9g5y'
        },
        __tabsterElementUID: 'm6ontm5kbjwwuqc0oa1thr48c|b|kwnkjy5j',
        [Symbol(SameObject caches)]: [Object: null prototype] {
          style: CSSStyleDeclaration {
            '0': '--tabster-deloser',
            _values: [Object],
            _importants: [Object],
            _length: 1,
            _onChange: [Function (anonymous)]
          }
        }
      }

      at Modalizer._setAccessibilityProps (../../node_modules/tabster/dist/tabster.cjs.development.js:5462:17)
      at new Modalizer (../../node_modules/tabster/dist/tabster.cjs.development.js:5341:11)
      at Tabster.ModalizerAPI.createModalizer (../../node_modules/tabster/dist/tabster.cjs.development.js:5735:21)
      at updateTabsterByAttribute (../../node_modules/tabster/dist/tabster.cjs.development.js:197:51)
      at processNode (../../node_modules/tabster/dist/tabster.cjs.development.js:6677:7)
      at Object.acceptNode (../../node_modules/tabster/dist/tabster.cjs.development.js:6646:14)
      at callTheUserObjectsOperation (../../node_modules/jsdom/lib/jsdom/living/generated/NodeFilter.js:26:30)
      at exports.filter (../../node_modules/jsdom/lib/jsdom/living/traversal/helpers.js:36:14)

```

**Comment by Hotell** [comment]
this issue is no longer present, closing
