### ISSUE TITLE
Pivot component throws in SSR

### ISSUE THREAD

**Issue by schandur** [microsoft/fluentui#22154]
### Environment Information

- **Package version(s)**: 8.60.2
- **Browser and OS versions**: Mac OS 11.6.1, Chrome 99.0.4844.51

#### Actual behavior:

Using a `Pivot` component in a server-side rendering setup throws the following exception in the browser console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'body')
    at FocusZone.componentDidMount (FocusZone.js:500:68)
    at eval (appendFunction.js:30:21)
    at Array.forEach (<anonymous>)
    at FocusZone.eval [as componentDidMount] (appendFunction.js:29:15)
    at commitLifeCycles (react-dom.development.js:3421:716)
    at commitLayoutEffects (react-dom.development.js:3959:465)
    at HTMLUnknownElement.callCallback (react-dom.development.js:657:119)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:677:45)
    at invokeGuardedCallback (react-dom.development.js:696:126)
    at commitRootImpl (react-dom.development.js:3915:28)
```

#### Expected behavior:

Pivot component should be rendered.

### Priorities and help requested:

The underlying reason appears to be this line in `FocusZone`'s `componentDidMount`:

`while (parentElement && parentElement !== this._getDocument().body && parentElement.nodeType === 1) {`

As we use `setSSR(true)`, the `_getDocument()` returns `undefined`.

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: N/A

**Comment by paulgildea** [comment]
@schandur Thanks for the issue.

Assigning to kick off investigation and repro.

**Comment by Hotell** [comment]
can you provide repro via https://stackblitz.com/ ? ty
