### ISSUE TITLE
[Bug]: yarn add @fluentui/react Not working!

### ISSUE THREAD

**Issue by marcus-castro-sp** [microsoft/fluentui#23086]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.35 GB / 15.60 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.52)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

Not possible

## Actual Behavior

1) Create a new React App using Yarn:

yarn create react-app my-app

2) Open the new app using VS Code:

cd my-app
code .

3) Install Fluent UI

yarn add @fluentui/react

I am getting the following error:

![image](https://user-images.githubusercontent.com/65231173/169350984-2ae8f37c-302b-4b4f-a2ed-3ea611bf3dfc.png)

## Expected Behavior
Library to be installed correctly.

### Logs

```shell
PS C:\Microsoft\BUGS\my-app> yarn add @fluentui/react
yarn add v1.22.10
[1/4] Resolving packages...
error Couldn't find package "@microsoft/load-themed-styles" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@microsoft/load-themed-styles" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Users\mmarcianorod\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:721:66)
    at new MessageError (C:\Users\mmarcianorod\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:750:123)
    at NpmResolver.<anonymous> (C:\Users\mmarcianorod\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:50684:15)
    at Generator.next (<anonymous>)
    at step (C:\Users\mmarcianorod\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
    at C:\Users\mmarcianorod\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
PS C:\Microsoft\BUGS\my-app>
```

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@marcus-castro-sp - thank you for filing this issue with. To set expectations, we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. However, I see you are willing contribute to this issue, that is great news! 
If you have a solution at hand and would like to contribute towards it, please, share your PR for us and the team will review it.
