### ISSUE TITLE
[Bug]: @griffel/babel-preset breaks `yarn start` in `@fluentui/react-components`

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#23978]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A, it does not depend on OS
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A

## Steps
- Clone the repo
- `yarn`
- `yarn start` and select `@fluentui/react-components`

> ### Alternative steps
> - in your existing fork/clone `rm -rf packages/react-components/react-components/lib-commonjs`
> - `yarn workspace @fluentui/react-components storybook`

## Actual Behavior

Build fails 💥

```
99% done plugins webpack-hot-middleware
webpack built preview 63d446c47d91106a3eaf in 20842ms
WARN Force closed manager build
ModuleBuildError: Module build failed (from ../../../node_modules/babel-loader/lib/index.js):
node:internal/modules/cjs/loader:464
throw e;
^

Error: Cannot find module '/office-ui-fabric-react/packages/react-components/react-components/lib-commonjs/index.js'
at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
at trySelf (node:internal/modules/cjs/loader:458:12)
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:24)
at Function.Module._resolveFilename (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:332:60)
at Module.resolve (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:127:23)
at Module.Object.assign.ensure (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:152:29)
at /office-ui-fabric-react/packages/react-components/react-components/src/Concepts/Positioning/PositioningFlipBoundary.stories.tsx:3:24
at /office-ui-fabric-react/packages/react-components/react-components/src/Concepts/Positioning/PositioningFlipBoundary.stories.tsx:32:3
at Script.runInContext (node:vm:139:12)
at Module.evaluate (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:293:12)
at evaluate (/office-ui-fabric-react/node_modules/@griffel/babel-preset/src/utils/evaluatePathsInVM.js:20:9)
at evaluatePathsInVM (/office-ui-fabric-react/node_modules/@griffel/babel-preset/src/utils/evaluatePathsInVM.js:75:21)
at evaluatePaths (/office-ui-fabric-react/node_modules/@griffel/babel-preset/src/utils/evaluatePaths.js:22:51)
at PluginPass.exit (/office-ui-fabric-react/node_modules/@griffel/babel-preset/src/transformPlugin.js:102:59)
at newFn (/office-ui-fabric-react/node_modules/@babel/traverse/lib/visitors.js:177:21)
at processResult (/office-ui-fabric-react/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:758:19)
at /office-ui-fabric-react/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:860:5
at /office-ui-fabric-react/node_modules/loader-runner/lib/LoaderRunner.js:399:11
at /office-ui-fabric-react/node_modules/loader-runner/lib/LoaderRunner.js:251:18
at context.callback (/office-ui-fabric-react/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
at /office-ui-fabric-react/node_modules/babel-loader/lib/index.js:59:103
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
ModuleBuildError: Module build failed (from ../../../node_modules/babel-loader/lib/index.js):
node:internal/modules/cjs/loader:464
throw e;
^

Error: Cannot find module '/office-ui-fabric-react/packages/react-components/react-components/lib-commonjs/index.js'
at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
at trySelf (node:internal/modules/cjs/loader:458:12)
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:24)
at Function.Module._resolveFilename (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:332:60)
at Module.resolve (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:127:23)
at Module.Object.assign.ensure (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:152:29)
at /office-ui-fabric-react/packages/react-components/react-components/src/Concepts/Positioning/PositioningOverflowBoundary.stories.tsx:3:24
at /office-ui-fabric-react/packages/react-components/react-components/src/Concepts/Positioning/PositioningOverflowBoundary.stories.tsx:33:3
at Script.runInContext (node:vm:139:12)
at Module.evaluate (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:293:12)
at evaluate (/office-ui-fabric-react/node_modules/@griffel/babel-preset/src/utils/evaluatePathsInVM.js:20:9)
at evaluatePathsInVM (/office-ui-fabric-react/node_modules/@griffel/babel-preset/src/utils/evaluatePathsInVM.js:75:21)
at evaluatePaths (/office-ui-fabric-react/node_modules/@griffel/babel-preset/src/utils/evaluatePaths.js:22:51)
at PluginPass.exit (/office-ui-fabric-react/node_modules/@griffel/babel-preset/src/transformPlugin.js:102:59)
at newFn (/office-ui-fabric-react/node_modules/@babel/traverse/lib/visitors.js:177:21)
at processResult (/office-ui-fabric-react/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:758:19)
at /office-ui-fabric-react/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:860:5
at /office-ui-fabric-react/node_modules/loader-runner/lib/LoaderRunner.js:399:11
at /office-ui-fabric-react/node_modules/loader-runner/lib/LoaderRunner.js:251:18
at context.callback (/office-ui-fabric-react/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
at /office-ui-fabric-react/node_modules/babel-loader/lib/index.js:59:103
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
✔ Would you like to send crash reports to Storybook? … yes
23% building 2/4 entries 816/891 dependencies 659/446 modulesnode:child_process:905
throw err;
^

Error: Command failed: start-storybook --port 3000 -s ./public --no-manager-cache
at checkExecSyncError (node:child_process:828:11)
at execSync (node:child_process:902:15)
at main (/office-ui-fabric-react/scripts/storybook/runner.js:63:3)
at Object.<anonymous> (/office-ui-fabric-react/scripts/storybook/runner.js:24:1)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
at node:internal/main/run_main_module:17:47 {
status: 1,
signal: null,
output: [ null, null, null ],
pid: 33854,
stdout: null,
stderr: null
}
error Command failed with exit code 1.
```

The suspicious part:

```
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:24)
at Function.Module._resolveFilename (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:332:60)
at Module.resolve (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:127:23)
at Module.Object.assign.ensure (/office-ui-fabric-react/node_modules/@griffel/babel-preset/node_modules/@linaria/babel-preset/lib/module.js:152:29)
```

It seems that `@griffel` preset is not excluded and there might be and issue with custom loader that removes it:

https://github.com/microsoft/fluentui/blob/7c1f041acfbebba3d84bbb69c31677808e9c41a0/.storybook/custom-loader.js#L10-L15

## Expected Behavior
Build is passing

## Workaround

Run `yarn buildto @fluentui/react-components`

### Logs

```shell
N/A
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
just to doublecheck/avoid confusion, in the error log there is `office-ui-fabric-react` I assume that's name of folder where have you cloned this repo correct ?

**Comment by layershifter** [comment]
> just to doublecheck/avoid confusion, in the error log there is `office-ui-fabric-react` I assume that's name of folder where have you cloned this repo correct ?

Yes, my fork is old and uses old repo name 🐱

**Comment by Hotell** [comment]
some initial troubleshooting, the logic correctly excludes `@griffel` in that custom-loader:

![image](https://user-images.githubusercontent.com/1223799/179801115-5540fcf0-63bb-48bd-821d-51ac3941d4ef.png)
