### ISSUE TITLE
[Bug]: `yarn buildci` does not work on Windows

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#24824]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 12.05 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.33), ChromiumDev (107.0.1379.1)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

Run `yarn buildci` from the repo root on Windows

## Actual Behavior

When running [yarn buildci](https://github.com/microsoft/fluentui/wiki/Build-Commands#yarn-buildci) on Windows the command errors out. When running on macOS the command succeeds.

## Expected Behavior

`yarn buildci` should execute successfully.

### Logs

```shell
ERR! [@fluentui/bundle-size test] ERROR DETECTED
ERR! started
ERR! hash: 7905aeae850099400bfc396a8b619e0195061a1a, cache hit? false
ERR! Running C:\Program Files\nodejs\npm.CMD run test
ERR!
ERR! > @fluentui/bundle-size@1.1.6 test
ERR! > jest
ERR!
ERR!  PASS   bundle-size  src/utils/calculateDiffByMetric.test.js (8.908 s)
ERR!  PASS   bundle-size  src/utils/readConfig.test.js (10.711 s)
ERR!   ● Console
ERR!
ERR!     console.log
ERR!       using config: C:\Users\SEANMO~1\AppData\Local\Temp\test-package-40908-4yyPLyWbMFyG\bundle-size.config.js
ERR!
ERR!       at readConfig (src/utils/readConfig.js:41:13)
ERR!
ERR!     console.log
ERR!       no config file found: undefined
ERR!        -> fallback to default config
ERR!
ERR!       at readConfig (src/utils/readConfig.js:34:15)
ERR!
ERR!     console.log
ERR!       using config: C:\Users\SEANMO~1\AppData\Local\Temp\test-package-40908-0JvELJ9KIgBb\bundle-size.config.js
ERR!
ERR!       at readConfig (src/utils/readConfig.js:41:13)
ERR!
ERR!     console.log
ERR!       using config: C:\Users\SEANMO~1\AppData\Local\Temp\test-package-40908-hBZXF2aFn1l6\bundle-size.config.js
ERR!
ERR!       at readConfig (src/utils/readConfig.js:41:13)
ERR!
ERR!     console.log
ERR!       using config: C:\Users\SEANMO~1\AppData\Local\Temp\test-package-40908-bMSDaJZdPG2I\bundle-size.config.js
ERR!
ERR!       at readConfig (src/utils/readConfig.js:41:13)
ERR!
ERR!  PASS   bundle-size  src/utils/compareResultsInReports.test.js
ERR!  PASS   bundle-size  src/utils/getChangedEntriesInReport.test.js
ERR!  PASS   bundle-size  src/reporters/cliReporter.test.js (12.057 s)
ERR!  PASS   bundle-size  src/utils/sortComparedReport.test.js
ERR!  PASS   bundle-size  src/utils/getRemoteReport.test.js
ERR!  PASS   bundle-size  src/utils/collectLocalReport.test.js (13.531 s)
ERR!  PASS   bundle-size  src/commands/compareReports.test.js (14.014 s)
ERR!  PASS   bundle-size  src/utils/prepareFixture.test.js (14.854 s)
ERR!  FAIL   bundle-size  src/utils/buildFixture.test.js (15.116 s)
ERR!   ● buildFixture › builds fixtures and returns minified & GZIP sizes
ERR!
ERR!     : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:
ERR!
ERR!       34 |   });
ERR!       35 |
ERR!     > 36 |   it('builds fixtures and returns minified & GZIP sizes', async () => {
ERR!          |   ^
ERR!       37 |     const fixturePath = await setup(`console.log('Hello world')`);
ERR!       38 |     const buildResult = await buildFixture(fixturePath, true);
ERR!       39 |
ERR!
ERR!       at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
ERR!       at Suite.<anonymous> (src/utils/buildFixture.test.js:36:3)
ERR!
ERR!  PASS   bundle-size  src/reporters/markdownReporter.test.js (6.113 s)
ERR!
ERR! Test Suites: 1 failed, 11 passed, 12 total
ERR! Tests:       1 failed, 22 passed, 23 total
ERR! Snapshots:   9 passed, 9 total
ERR! Time:        26.203 s
ERR! Ran all test suites.
ERR! npm ERR! Lifecycle script `test` failed with error:
ERR! npm ERR! Error: command failed
ERR! npm ERR!   in workspace: @fluentui/bundle-size@1.1.6
ERR! npm ERR!   at location: C:\Users\seanmonahan\Documents\dev\fluentui\packages\bundle-size
ERR! failed
info ----------------------------------------------
info Took a total of 54.27s to complete
error Command failed with exit code 1.
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
I added this to vbuild for the moment. We might need to confirm where incoming build related issues should be kept going forward.
