### ISSUE TITLE
[Bug]: adding Fluent UI v9 to build causing out of memory error with Webpack build

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#24952]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Azure DevOps build machine, Windows.
```

### Are you reporting Accessibility issue?

no

### Reproduction

See description

## Actual Behavior

Adding Fluent UI v9 to a project causes Webpack builds to fail with an out of memory error.

This is a project that currently uses Fluent v8 and it moving toward Fluent v9 so it currently includes both versions. Prior to adding v9 there were no issues with the build.

#### --max-old-space-size

The [--max-old-space-size](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes) flag was set to increase the amount of memory available to Node. This helped somewhat but the build still failed ~90% of the time.

#### Try a different UI library

One theory is that the project's build was reaching some sort of tipping point and adding Fluent v9 just happened to be the thing that tipped it over. We can test this theory by removing Fluent v9 and replacing it with a comparable library. If the build continues to fail then the issue is likely with the project, Webpack configuration, or something along those lines. If the build passes then we should probably look at Fluent v9 more closely.

We removed Fluent v9 and replaced it with [Material UI](https://mui.com/material-ui/getting-started/overview/) and the build passed. This indicates the issue lies in Fluent v9 and we should focus our investigations there next.

## Expected Behavior

Fluent UI v9 should not cause Webpack builds to fail

### Logs

```shell
Webpack error message:

Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
    at new NodeError (node:internal/errors:371:5)
    at Worker.[kOnExit] (node:internal/worker:276:26)
    at Worker.<computed>.onexit (node:internal/worker:198:20)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnExit] (node:internal/worker:276:12)
    at Worker.<computed>.onexit (node:internal/worker:198:20) {
  code: 'ERR_WORKER_OUT_OF_MEMORY'
}
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@Hotell I've assigned this to you for now since we've previously discussed this. LMK if you need any more info.

**Comment by spmonahan** [comment]
@ShrutiJaiswal1494 Opened an issue to track your Webpack out of memory error.

**Comment by layershifter** [comment]
@spmonahan I suggest to check if that  somehow related to `@fluentui/react-icons` (check if `source-map-loader` is present in a config). I used v9 in a pet project and adding imports from it make reloads extremely slow.

**Comment by ShrutiJaiswal1494** [comment]
@layershifter Seems like after removing the @fluentui/react-icons package, we are not having the memory issue. Is there something wrong with the package.

**Comment by layershifter** [comment]
> @layershifter Seems like after removing the @fluentui/react-icons package, we are not having the memory issue. Is there something wrong with the package?

I don't think that there is something wrong, we even made few rounds of optimisations for the package before 🤔 

However, as I said I noticed that it caused issues in Next.js environment. I don't think that you are using Next.js, so it will be good to understand what causes problems and fix them 🐱

**Comment by KerimG** [comment]
Could https://github.com/microsoft/fluentui/issues/25547 be related?

**Comment by Hotell** [comment]
thanks all for additional context! 

It looks like react-icons is indeed the culprit (https://github.com/microsoft/fluentui/issues/25547#issuecomment-1305621502). now we need to find out why.

**Comment by kboul** [comment]
I also get this error. More specifically I get 
`2023-12-19 14:44:29 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
2023-12-19 14:44:29  1: 0xa2f388 node::Abort() [/usr/local/bin/node]
2023-12-19 14:44:29  2: 0x975a58 node::FatalError(char const*, char const*) [/usr/local/bin/node]
2023-12-19 14:44:29  3: 0xb94c98 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
2023-12-19 14:44:29  4: 0xb94e24 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
2023-12-19 14:44:29  5: 0xd3d558 v8::internal::Heap::EnsureFromSpaceIsCommitted() [/usr/local/bin/node]
2023-12-19 14:44:29  6: 0xd3dfc0  [/usr/local/bin/node]
2023-12-19 14:44:29  7: 0xd4bc84 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
2023-12-19 14:44:29  8: 0xd4f154 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
2023-12-19 14:44:29  9: 0xd21444 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
2023-12-19 14:44:29 10: 0x103c66c v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
2023-12-19 14:44:29 11: 0x139ee0c  [/usr/local/bin/node]
2023-12-19 14:44:30 Aborted
2023-12-19 14:44:30 npm ERR! code ELIFECYCLE`

when upgrading fluent from version **9.20.3** to **9.40.0**

**Comment by xxronis** [comment]
For the same upgrade from 9.20.3 to 9.40, after setting a memory limit of 16GB! for the node process we get:
```
RangeError: Invalid string length
    at ConcatSource.source(/app/node_modules/webpack-sources/lib/Concats
    ource.js:42:56)
    at writeOut(/app/node_modules/webpack/lib/Compiler.js:454:29)
    /app/node_modules/webpack/lib/Compiler.js:476:7
    at arrayIterator(/app/node_modules/neo-async/async.js:3467:9)
    at timesSync(/app/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit(/app/node_modules/neo-async/async.js:3463:5
    at emitFiles(/app/node_modules/webpack/lib/Compiler.js:358:13)
    at /app/node_modules/mkdirp/index.js:49:26
    at FSReqCallback.oncomplete(node:fs:200:5)
```
This is on webpack 4

**Comment by Hotell** [comment]
@kboul @xxronis can you provide repro ?

can folks confirm this is still an issue or we can close this one ? @spmonahan @ShrutiJaiswal1494 @layershifter  ?

**Comment by kboul** [comment]
@Hotell The issue was solved when we upgraded to webpack 5.

**Comment by spmonahan** [comment]
> @kboul @xxronis can you provide repro ?
> 
> can folks confirm this is still an issue or we can close this one ? @spmonahan @ShrutiJaiswal1494 @layershifter ?

I just filed this because I was on Shield so I cannot confirm either way.

**Comment by 15MariamS** [comment]
👋 I'm getting this error when upgrading from `9.47.5` in two different environments
