### ISSUE TITLE
[Bug]: https://developer.microsoft.com/en-us/fluentui crashes and is empty

### ISSUE THREAD

**Issue by pelikhan** [microsoft/fluentui#25299]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Try loading https://developer.microsoft.com/en-us/fluentui in Edge
```

### Are you reporting Accessibility issue?

no

### Reproduction

Navigate to https://developer.microsoft.com/en-us/fluentui

## Actual Behavior
fill this out

## Expected Behavior
fill this out

### Logs

```shell
ReferenceError: devConsole is not defined
    at HTMLDocument.<anonymous> (common-nav.min.js?v=3.0:9:33454)
    at j (jquery-2.1.1.min.js:2:26860)
    at Object.add [as done] (jquery-2.1.1.min.js:2:27169)
    at n.fn.ready (jquery-2.1.1.min.js:2:29275)
    at common-nav.min.js?v=3.0:9:33424
    at Object.execCb (require.min.js:29:311)
    at Z.check (require.min.js:18:385)
    at Z.<anonymous> (require.min.js:23:9)
    at require.min.js:8:102
    at require.min.js:23:369
```

### Requested priority

Blocking

### Products/sites affected

https://developer.microsoft.com/en-us/fluentui

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by thoffmann-fms** [comment]
https://fabricweb.azureedge.net/fabric-website/manifests/v8-prod.js is generating an HTTP 409 error.
![image](https://user-images.githubusercontent.com/28546239/196779482-75e662e7-1560-471f-83f0-3644d7752806.png)
