### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by japamatSynapse** [microsoft/fluentui#25302]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
Google chrome: Version 106.0.5249.119 (Official Build) (arm64)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui

### Bug Description
not a bug directly with the library but the docs page is down

## Actual Behavior
![image](https://user-images.githubusercontent.com/56046697/196783125-f43e26cd-0f5b-467b-948e-c14fb6647ef2.png)

## Expected Behavior
The docs should render

### Logs

```shell
ReferenceError: devConsole is not defined
    at HTMLDocument.<anonymous> (common-nav.min.js?v=3.0:9:33454)
    at j (jquery-2.1.1.min.js:2:26860)
    at Object.add [as done] (jquery-2.1.1.min.js:2:27169)
    at n.fn.ready (jquery-2.1.1.min.js:2:29275)
    at common-nav.min.js?v=3.0:9:33424
    at Object.execCb (require.min.js:29:311)
    at Z.check (require.min.js:18:385)
    at Z.<anonymous> (require.min.js:23:9)
    at require.min.js:8:102
    at require.min.js:23:369
```

### Requested priority

High

### Products/sites affected

https://developer.microsoft.com/en-us/fluentui

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by japamatSynapse** [comment]
Docs are back up - closing.
