### ISSUE TITLE
[Bug]: Slider component produces hydration error

### ISSUE THREAD

**Issue by ahmadsoe** [microsoft/fluentui#25390]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.19 undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz
    Memory: 2.36 GB / 9.60 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  Browsers:
    Chromium: 106.0.5249.91
    Firefox: 105.0.2
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/p/github/codesandbox/codesandbox-template-next.js/csb-qld81n/draft/cocky-neco?file=%2Fpages%2Findex.tsx

## Actual Behavior
`Slider` component does not render properly on the server without `step` props and produces hydration error.

## Expected Behavior
Since Fluent UI v9 fully supports Server-Side Rendering, `Slider` component should render properly even without `step` props.

### Logs

```shell
Warning: Prop `style` did not match. Server: "--fui-Slider--direction:90deg;--fui-Slider--progress:20%" Client: "--fui-Slider--direction:90deg;--fui-Slider--steps-percent:;--fui-Slider--progress:20%"
    at div
    at eval (webpack-internal:///./node_modules/@fluentui/react-slider/lib/components/Slider/Slider.js:19:79)
    at Home
    at div
    at TextDirectionProvider (webpack-internal:///./node_modules/@griffel/react/TextDirectionContext.esm.js:20:3)
    at eval (webpack-internal:///./node_modules/@fluentui/react-provider/lib/components/FluentProvider/FluentProvider.js:17:95)
    at SSRProvider (webpack-internal:///./node_modules/@fluentui/react-utilities/lib/ssr/SSRContext.js:41:54)
    at RendererProvider (webpack-internal:///./node_modules/@griffel/react/RendererContext.esm.js:30:3)
    at MyApp (webpack-internal:///./pages/_app.tsx:40:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:359:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:794:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:916:27) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
This is rather a problem with next.js which will not render style properties with empty strings. Here is a repro you can use to trigger an issue on their end: https://codesandbox.io/p/github/codesandbox/codesandbox-template-next.js/csb-il0k5t/draft/clever-wing

We have our own SSR tests that use only react and this does not repro there, because the expected behaviour that an inline style property with an empty string as value is rendered on both server an client
