### ISSUE TITLE
[Bug]: Use instruction to Setup (configuring development environment) issue

### ISSUE THREAD

**Issue by love89music** [microsoft/fluentui#25400]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 PRO 4650U with Radeon Graphics
    Memory: 4.60 GB / 15.23 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://github.com/microsoft/fluentui/wiki/Setup

### Bug Description

Reproduce: 

1. Use this [instruction](https://github.com/microsoft/fluentui/wiki/Setup) https://github.com/microsoft/fluentui/wiki/Setup to Setup (configuring development environment) issue. When execute yarn start and chose @fluentui/react , errors is there. Please help us to run fluent demo.

2. Use the latest code from https://github.com/microsoft/fluentui

3. C:\Users>yarn -v
1.22.19
C:\Users>npm -v
7.24.2

4. We can not start fluent ui demo right now, please help us.

Errors:
PS C:\AAA\fluentui-master> yarn start
yarn run v1.23.34
$ node scripts/start.js
√ Which project to start (select or type partial name)? » @fluentui/react
$ cross-env NODE_OPTIONS=--max-old-space-size=3072 just-scripts dev:storybook
[14:10:15] ■ started 'dev:storybook'
[14:10:15] ■ started 'storybook:start'
node heap limit = 3120 MB
-------------- main
-------------- config
[14:10:17] x Error detected while running 'storybook:start'
[14:10:17] x ------------------------------------
[14:10:17] x **_Error: No configuration files have been found in your configDir (C:\packages\react-examples\.storybook).
Storybook needs either a "main" or "config" file._**
    at validateConfigurationFiles (C:\AAA\fluentui-master\node_modules\@storybook\core-common\dist\cjs\utils\validate-configuration-files.js:51:11)
    at loadCustomPresets (C:\AAA\fluentui-master\node_modules\@storybook\core-common\dist\cjs\utils\load-custom-presets.js:19:62)
    at loadAllPresets (C:\AAA\fluentui-master\node_modules\@storybook\core-common\dist\cjs\presets.js:357:131)
    at buildDevStandalone (C:\AAA\fluentui-master\node_modules\@storybook\core-server\dist\cjs\build-dev.js:108:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\AAA\fluentui-master\scripts\tasks\storybook.ts:81:5
[14:10:17] x ------------------------------------
[14:10:17] x finished 'dev:storybook' in 1.36s with errors
[14:10:17] x Error previously detected. See above for error messages.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\AAA\fluentui-master\.yarn\releases\cli.js start
Directory: C:\AAA\fluentui-master\packages\react
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
Done in 117.88s. Peak memory usage 34.11MB.

### Logs

```shell
no
```

### Requested priority

High

### Products/sites affected

sites

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hi @love89music, do you have a repo I could clone to take a look at this issue?
