### ISSUE TITLE
[Feature]:  FluentUI v8 setup in Next.js 13 app directory

### ISSUE THREAD

**Issue by mahish** [microsoft/fluentui#25418]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

Enable usage of FluentUI v8 with the new `app` folder introduced by Next.js v13, particulary SSR support as documented here for the previous Next.js versions https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing.

### Additional context

I tried to migrate code from `_document` to the root `layout` but I was unable to use the `Stylesheet` class https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/merge-styles/src/Stylesheet.ts#L103

and got:

```
error - TypeError: Class extends value undefined is not a constructor or null
    at Object.__extends (webpack-internal:///(sc_server)/./node_modules/tslib/tslib.js:73:58)
    at eval (webpack-internal:///(sc_server)/./node_modules/@fluentui/utilities/lib-commonjs/BaseComponent.js:21:13)
    at eval (webpack-internal:///(sc_server)/./node_modules/@fluentui/utilities/lib-commonjs/BaseComponent.js:189:2)
    at Object.(sc_server)/./node_modules/@fluentui/utilities/lib-commonjs/BaseComponent.js (…/.next/server/app/test/page.js:10766:1)
    at __webpack_require__ (…/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/@fluentui/utilities/lib-commonjs/index.js:23:23)
    at Object.(sc_server)/./node_modules/@fluentui/utilities/lib-commonjs/index.js (…/.next/server/app/test/page.js:11338:1)
    at __webpack_require__ (…/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/@fluentui/style-utilities/lib-commonjs/utilities/icons.js:7:19)
    at Object.(sc_server)/./node_modules/@fluentui/style-utilities/lib-commonjs/utilities/icons.js (…/.next/server/app/test/page.js:10458:1) {
  type: 'TypeError',
  page: '/test'
}
```

There is the existing discussion thread for v9: https://github.com/microsoft/fluentui/discussions/25384 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mahish** [comment]
Hi, is there no plan to support Next.js v13 app folder https://nextjs.org/docs/app/building-your-application/routing#the-app-router ? Thanks.

**Comment by khmakoto** [comment]
Reopening this issue

**Comment by mahish** [comment]
Hi, as I can see, there is official support for SSR (and Next.js specifically) for v9: https://react.fluentui.dev/?path=/docs/concepts-developer-server-side-rendering-next-js-appdir-setup--page . 

How about v8: https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing ? is there no plan to support Next.js v13+ app folder https://nextjs.org/docs/app/building-your-application/routing#the-app-router ? Thanks.
