### ISSUE TITLE
[Bug]: Cards not compatible with React 18

### ISSUE THREAD

**Issue by elliot-huffman** [microsoft/fluentui#26653]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 16.60 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.70)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/async-wood-bd02mn?file=/src/App.tsx

## Actual Behavior
Page renders blank

## Expected Behavior
Render the UI

### Logs

```shell
Warning: React has detected a change in the order of Hooks called by CardHeader. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useRef                     useRef
3. useContext                 useContext
4. useContext                 useContext
5. useId                      useEffect
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at eval (https://bd02mn.csb.app/node_modules/@fluentui/react-card/lib-commonjs/components/CardHeader/CardHeader.js:15:33)
    at div
    at eval (https://bd02mn.csb.app/node_modules/@fluentui/react-card/lib-commonjs/components/CardPreview/CardPreview.js:15:34)
    at div
    at eval (https://bd02mn.csb.app/node_modules/@fluentui/react-card/lib-commonjs/components/Card/Card.js:16:27)
    at App (https://bd02mn.csb.app/src/App.tsx:29:29)
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by elliot-huffman** [comment]
@micahgodbolt I think this has to do with back-end deps. I am getting a lot of wierd deps warnings with the latest version.

**Comment by elliot-huffman** [comment]
This used to work in v9.11 I think, it stopped working with the most resent updates.

**Comment by ahmed-adly-khalil** [comment]
any luck here?, this broke the card header component

**Comment by sopranopillow** [comment]
Hey @elliot-huffman, I checked with the provided repro and #26745 fixes this issue.

**Comment by elliot-huffman** [comment]
Once it gets published in a release, I will test it and if it is fixed on my side, I will close the issue :)
Thanks for getting the issue fixed so fast!

**Comment by elliot-huffman** [comment]
@sopranopillow  QQ did you happen to fix the issue with the dependencies that seems to be related?
I wasn't able to capture the below issue in the repro space since it doesn't expose the NPM install command.

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN Found: @types/react@18.0.27
npm WARN node_modules/@types/react
npm WARN   dev @types/react@"^18.0.27" from the root project
npm WARN   55 more (@fluentui/foundation-legacy, @fluentui/react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @types/react@">=16.8.0 <18.0.0" from @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN node_modules/@fluentui/react-components/node_modules/@fluentui/react-virtualizer
npm WARN   @fluentui/react-virtualizer@"9.0.0-alpha.3" from @fluentui/react-components@9.14.0
npm WARN   node_modules/@fluentui/react-components
npm WARN 
npm WARN Conflicting peer dependency: @types/react@17.0.53
npm WARN node_modules/@types/react
npm WARN   peer @types/react@">=16.8.0 <18.0.0" from @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN   node_modules/@fluentui/react-components/node_modules/@fluentui/react-virtualizer
npm WARN     @fluentui/react-virtualizer@"9.0.0-alpha.3" from @fluentui/react-components@9.14.0
npm WARN     node_modules/@fluentui/react-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN Found: @types/react-dom@18.0.10
npm WARN node_modules/@types/react-dom
npm WARN   dev @types/react-dom@"^18.0.10" from the root project
npm WARN   43 more (@fluentui/react, @fluentui/react-accordion, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @types/react-dom@">=16.8.0 <18.0.0" from @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN node_modules/@fluentui/react-components/node_modules/@fluentui/react-virtualizer
npm WARN   @fluentui/react-virtualizer@"9.0.0-alpha.3" from @fluentui/react-components@9.14.0
npm WARN   node_modules/@fluentui/react-components
npm WARN 
npm WARN Conflicting peer dependency: @types/react-dom@17.0.18
npm WARN node_modules/@types/react-dom
npm WARN   peer @types/react-dom@">=16.8.0 <18.0.0" from @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN   node_modules/@fluentui/react-components/node_modules/@fluentui/react-virtualizer
npm WARN     @fluentui/react-virtualizer@"9.0.0-alpha.3" from @fluentui/react-components@9.14.0
npm WARN     node_modules/@fluentui/react-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   60 more (@fluentui/foundation-legacy, @fluentui/react, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@">=16.8.0 <18.0.0" from @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN node_modules/@fluentui/react-components/node_modules/@fluentui/react-virtualizer
npm WARN   @fluentui/react-virtualizer@"9.0.0-alpha.3" from @fluentui/react-components@9.14.0
npm WARN   node_modules/@fluentui/react-components
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@">=16.8.0 <18.0.0" from @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN   node_modules/@fluentui/react-components/node_modules/@fluentui/react-virtualizer
npm WARN     @fluentui/react-virtualizer@"9.0.0-alpha.3" from @fluentui/react-components@9.14.0
npm WARN     node_modules/@fluentui/react-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   44 more (@fluentui/react, @fluentui/react-accordion, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@">=16.8.0 <18.0.0" from @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN node_modules/@fluentui/react-components/node_modules/@fluentui/react-virtualizer
npm WARN   @fluentui/react-virtualizer@"9.0.0-alpha.3" from @fluentui/react-components@9.14.0
npm WARN   node_modules/@fluentui/react-components
npm WARN
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@">=16.8.0 <18.0.0" from @fluentui/react-virtualizer@9.0.0-alpha.3
npm WARN   node_modules/@fluentui/react-components/node_modules/@fluentui/react-virtualizer
npm WARN     @fluentui/react-virtualizer@"9.0.0-alpha.3" from @fluentui/react-components@9.14.0
npm WARN     node_modules/@fluentui/react-components
```

**Comment by sopranopillow** [comment]
Looks like the dependency issue is with `@fluentui/react-virtualizer` seems like that package doesn't support React 18 as it mentiones `react-dom@">=16.8.0 <18.0.0"` and `@types/react@">=16.8.0 <18.0.0"`. This would be a separate issue from the original one, would you mind filing another issue for it?

**Comment by elliot-huffman** [comment]
sure thing, how do I handle the mandatory repo link that the issue form requires for something like this?

**Comment by sopranopillow** [comment]
You could try to replicate the dependencies in the codesandbox and that should repro the error

**Comment by elliot-huffman** [comment]
FYI, this issue is resolved. Tested and working :)

**Comment by elliot-huffman** [comment]
> You could try to replicate the dependencies in the code sandbox and that should repro the error.

The problem is that the issue is produced during dependency install, not after. The warnings are because the package manager found conflicting version requirements.
