### ISSUE TITLE
[Bug]: React Hook Form - Not compatible in TextField

### ISSUE THREAD

**Issue by rcapulsuhay** [microsoft/fluentui#27226]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Compiled with problems:
×
ERROR
Cannot set property value of #<TextFieldBase> which has only a getter
TypeError: Cannot set property value of #<TextFieldBase> which has only a getter
    at setFieldValue (http://localhost:3000/static/js/bundle.js:51178:36)
    at updateValidAndValue (http://localhost:3000/static/js/bundle.js:51041:176)
    at ref (http://localhost:3000/static/js/bundle.js:51453:11)
    at commitAttachRef (http://localhost:3000/static/js/bundle.js:36004:24)
    at commitLayoutEffectOnFiber (http://localhost:3000/static/js/bundle.js:35885:13)
    at commitLayoutMountEffects_complete (http://localhost:3000/static/js/bundle.js:36884:13)
    at commitLayoutEffects_begin (http://localhost:3000/static/js/bundle.js:36873:11)
    at commitLayoutEffects (http://localhost:3000/static/js/bundle.js:36819:7)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:38729:9)
    at commitRoot (http://localhost:3000/static/js/bundle.js:38609:9)
ERROR
Cannot set property value of #<TextFieldBase> which has only a getter
TypeError: Cannot set property value of #<TextFieldBase> which has only a getter
    at setFieldValue (http://localhost:3000/static/js/bundle.js:51178:36)
    at updateValidAndValue (http://localhost:3000/static/js/bundle.js:51041:176)
    at ref (http://localhost:3000/static/js/bundle.js:51453:11)
    at commitAttachRef (http://localhost:3000/static/js/bundle.js:36004:24)
    at commitLayoutEffectOnFiber (http://localhost:3000/static/js/bundle.js:35885:13)
    at commitLayoutMountEffects_complete (http://localhost:3000/static/js/bundle.js:36884:13)
    at commitLayoutEffects_begin (http://localhost:3000/static/js/bundle.js:36873:11)
    at commitLayoutEffects (http://localhost:3000/static/js/bundle.js:36819:7)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:38729:9)
    at commitRoot (http://localhost:3000/static/js/bundle.js:38609:9)
```

### Are you reporting Accessibility issue?

None

### Reproduction

n/a

### Bug Description

Compiled with problems:
×
ERROR
Cannot set property value of #<TextFieldBase> which has only a getter
TypeError: Cannot set property value of #<TextFieldBase> which has only a getter
    at setFieldValue (http://localhost:3000/static/js/bundle.js:51178:36)
    at updateValidAndValue (http://localhost:3000/static/js/bundle.js:51041:176)
    at ref (http://localhost:3000/static/js/bundle.js:51453:11)
    at commitAttachRef (http://localhost:3000/static/js/bundle.js:36004:24)
    at commitLayoutEffectOnFiber (http://localhost:3000/static/js/bundle.js:35885:13)
    at commitLayoutMountEffects_complete (http://localhost:3000/static/js/bundle.js:36884:13)
    at commitLayoutEffects_begin (http://localhost:3000/static/js/bundle.js:36873:11)
    at commitLayoutEffects (http://localhost:3000/static/js/bundle.js:36819:7)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:38729:9)
    at commitRoot (http://localhost:3000/static/js/bundle.js:38609:9)
ERROR
Cannot set property value of #<TextFieldBase> which has only a getter
TypeError: Cannot set property value of #<TextFieldBase> which has only a getter
    at setFieldValue (http://localhost:3000/static/js/bundle.js:51178:36)
    at updateValidAndValue (http://localhost:3000/static/js/bundle.js:51041:176)
    at ref (http://localhost:3000/static/js/bundle.js:51453:11)
    at commitAttachRef (http://localhost:3000/static/js/bundle.js:36004:24)
    at commitLayoutEffectOnFiber (http://localhost:3000/static/js/bundle.js:35885:13)
    at commitLayoutMountEffects_complete (http://localhost:3000/static/js/bundle.js:36884:13)
    at commitLayoutEffects_begin (http://localhost:3000/static/js/bundle.js:36873:11)
    at commitLayoutEffects (http://localhost:3000/static/js/bundle.js:36819:7)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:38729:9)
    at commitRoot (http://localhost:3000/static/js/bundle.js:38609:9)

### Requested priority

High

### Products/sites affected

asdasd

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @rcapulsuhay, thanks for the bug report. Could you please provide a codepen or codesandbox with a repro?

A quick guess as to the problem based on the error logs: you likely need to use react-hook-form's `Controller` around the `TextField`: https://react-hook-form.com/api/usecontroller/controller/
