### ISSUE TITLE
[Bug]: FormDatepicker throws unexpected console error

### ISSUE THREAD

**Issue by kavinkuma6** [microsoft/fluentui#27484]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
Used https://codesandbox.io/
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/vigilant-robinson-cbnppm?file=/components/DatePicker.jsx

### Bug Description

This is related to `FormDatePicker` component.
As mentioned in the [docs](https://fluentsite.z22.web.core.windows.net/0.66.2/components/form/props#form-datepicker) I am passing a primitive ShorthandValue type(string) to `errorMessage`. And the error message is getting rendered as expected below the field. 

## Actual Behavior
But, an unexpected console error as attached in the logs section is thrown

## Expected Behavior
Console error should not be thrown

### Logs

```shell
Warning: Received `true` for a non-boolean attribute `error`.

If you want to write it to the DOM, pass a string instead: error="true" or error={value.toString()}.
    at div
    at eval (https://cbnppm.csb.app/node_modules/@fluentui/react-northstar/dist/es/components/Datepicker/Datepicker.js:50:59)
    at div
    at eval (https://cbnppm.csb.app/node_modules/@fluentui/react-bindings/dist/es/compose/compose.js:15:27)
    at Datepicker (https://cbnppm.csb.app/components/DatePicker.jsx:12:12)
    at exports.Controller (https://cbnppm.csb.app/node_modules/react-hook-form/dist/index.cjs.js:1:21451)
    at form
    at eval (https://cbnppm.csb.app/node_modules/@fluentui/react-northstar/dist/es/components/Form/Form.js:25:59)
    at HolidayForm (https://cbnppm.csb.app/HolidayForm.jsx:30:50)
    at div
    at eval (https://cbnppm.csb.app/node_modules/@fluentui/react-northstar/dist/es/components/Flex/Flex.js:21:59)
    at div
    at RendererProvider (https://cbnppm.csb.app/node_modules/@fluentui/react-northstar-fela-renderer/dist/es/RendererProvider.js:28:30)
    at Provider (https://cbnppm.csb.app/node_modules/@fluentui/react-northstar-fela-renderer/dist/es/createFelaRenderer.js:64:31)
    at Provider (https://cbnppm.csb.app/node_modules/@fluentui/react-northstar/dist/es/components/Provider/Provider.js:68:26)
​
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sumitshinde-84** [comment]
I would like to work on this issue,  can you please assign it to me?
