### ISSUE TITLE
[Docs]: Document that `Overflow` components need to be wrapped around components that forward ref

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#27652]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 51.85 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/wandering-morning-to0rl6?file=/example.tsx:2082-2106

## Actual Behavior
I am trying to make customized component that is being wrapped by `OverflowItem`. 

The code looks like:
```
//  customized component
const ItemVisible = (props) => {
  const isVisible = useIsOverflowItemVisible(props.id);

  console.log("Item is visible", isVisible);
  return <Button>Item {props.id}</Button>;
};

export const Default = () => {
  const styles = useStyles();

  const itemIds = new Array(8).fill(0).map((_, i) => i.toString());

  return (
    <Overflow>
      <div className={mergeClasses(styles.container, styles.resizableArea)}>
        {itemIds.map((i) => (
          <OverflowItem key={i} id={i}>
            <ItemVisible id={i} /> // customized component
          </OverflowItem>
        ))}

        <OverflowMenu itemIds={itemIds} />
      </div>
    </Overflow>
  );
};
```
Because I want to use `useIsOverflowItemVisible` in the customized ItemVisible component to do some extra behavior. However, I got the error in the console:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef`.
    at ItemVisible (https://to0rl6.csb.app/example.tsx:103:74)
    at eval (https://to0rl6.csb.app/node_modules/@fluentui/react-overflow/lib-commonjs/components/OverflowItem/OverflowItem.js:14:13)
    at div
    at Provider (https://to0rl6.csb.app/node_modules/@fluentui/react-context-selector/lib-commonjs/createContext.js:16:46)
    at eval (https://to0rl6.csb.app/node_modules/@fluentui/react-overflow/lib-commonjs/components/Overflow.js:29:20)
    at Default (https://to0rl6.csb.app/example.tsx:115:18)
    at div
    at TextDirectionProvider (https://to0rl6.csb.app/node_modules/@griffel/react/TextDirectionContext.esm.js:23:33)
    at eval (https://to0rl6.csb.app/node_modules/@fluentui/react-provider/lib-commonjs/components/FluentProvider/FluentProvider.js:16:69)
```
And the overflow does not work, `useIsOverflowItemVisible` always return false even the items are visible. 

## Expected Behavior
I would expect there is no error, and `useIsOverflowItemVisible` can be used and return correct result in customized component that is wrapped in `OverflowItem`. 

### Logs

```shell
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef`.
    at ItemVisible (https://to0rl6.csb.app/example.tsx:103:74)
    at eval (https://to0rl6.csb.app/node_modules/@fluentui/react-overflow/lib-commonjs/components/OverflowItem/OverflowItem.js:14:13)
    at div
    at Provider (https://to0rl6.csb.app/node_modules/@fluentui/react-context-selector/lib-commonjs/createContext.js:16:46)
    at eval (https://to0rl6.csb.app/node_modules/@fluentui/react-overflow/lib-commonjs/components/Overflow.js:29:20)
    at Default (https://to0rl6.csb.app/example.tsx:115:18)
    at div
    at TextDirectionProvider (https://to0rl6.csb.app/node_modules/@griffel/react/TextDirectionContext.esm.js:23:33)
    at eval (https://to0rl6.csb.app/node_modules/@fluentui/react-provider/lib-commonjs/components/FluentProvider/FluentProvider.js:16:69)
```

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by flora8984461** [comment]
@ling1726 thank you! The part makes OverflowItem needs ref being forwarded is it here? The ref is being used to render child element? 

https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-overflow/src/components/OverflowItem/OverflowItem.tsx#L15

**Comment by barbalex** [comment]
I spent a half hour trying to get Overflow components work. Finally fount this crucial information. Please add it to the docs
