### ISSUE TITLE
[Bug]: @fluentui/react-datepicker-compat Controlled DatePicker Component with Empty Initial Value

### ISSUE THREAD

**Issue by pradeept95** [microsoft/fluentui#27955]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
Not Applicable
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/lucid-rgb-lokp47

## Actual Behavior
Whenever we have a controlled date picker with an empty initial value (like null or "") it is throwing an error and not working expected.

VM2685 vendors~app~embed~sandbox-startup.b754f8b0e.chunk.js:1 A component is changing a controlled value to be uncontrolled. This is likely caused by the value changing from defined to an undefined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components Error
    at eval (https://lokp47.codesandbox.io/node_modules/@fluentui/react-utilities/lib-commonjs/hooks/useControllableState.js:42:31)
    at invokePassiveEffectCreate (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:23487:20)
    at HTMLUnknownElement.callCallback (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:23574:9)
    at unstable_runWithPriority (https://lokp47.codesandbox.io/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:23447:14)
    at eval (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:23324:11)
    at workLoop (https://lokp47.codesandbox.io/node_modules/scheduler/cjs/scheduler.development.js:417:34)
    at flushWork (https://lokp47.codesandbox.io/node_modules/scheduler/cjs/scheduler.development.js:390:14)
    at MessagePort.performWorkUntilDeadline (https://lokp47.codesandbox.io/node_modules/scheduler/cjs/scheduler.development.js:157:27) 
    in DatePicker (created by Controlled)
    in Controlled

## Expected Behavior
If the value is an either null or empty string (except undefined) with onSelectDate callback, it should work properly as a controlled input. OR there should be a way to define controlled DatePicker without any date selected initially.

### Logs

```shell
VM2685 vendors~app~embed~sandbox-startup.b754f8b0e.chunk.js:1 A component is changing a controlled value to be uncontrolled. This is likely caused by the value changing from defined to an undefined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components Error
    at eval (https://lokp47.codesandbox.io/node_modules/@fluentui/react-utilities/lib-commonjs/hooks/useControllableState.js:42:31)
    at invokePassiveEffectCreate (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:23487:20)
    at HTMLUnknownElement.callCallback (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:23574:9)
    at unstable_runWithPriority (https://lokp47.codesandbox.io/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:23447:14)
    at eval (https://lokp47.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:23324:11)
    at workLoop (https://lokp47.codesandbox.io/node_modules/scheduler/cjs/scheduler.development.js:417:34)
    at flushWork (https://lokp47.codesandbox.io/node_modules/scheduler/cjs/scheduler.development.js:390:14)
    at MessagePort.performWorkUntilDeadline (https://lokp47.codesandbox.io/node_modules/scheduler/cjs/scheduler.development.js:157:27) 
    in DatePicker (created by Controlled)
    in Controlled
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ehmPlankje** [comment]
This ticket appears to be a duplicate of the issue that I opened 2 days ago: https://github.com/microsoft/fluentui/issues/27931
