### ISSUE TITLE
[Bug]: TypeError: _interop_require_wildcard._ is not a function  in React 

### ISSUE THREAD

**Issue by vcpavao** [microsoft/fluentui#29107]
### Library

react-components / v9 (@fluentui/react-components)

### System Info

```shell
Node v.18.0.0, React: ^17.0.2, 

System:
    OS: macOS 13.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 99.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.6
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A - code sandbox does not allow for replicating issues with installs/packages

## Actual Behavior
```
Runtime error: 
TypeError: _interop_require_wildcard._ is not a function 
at ./node_modules/@fluentui/react-portal-compat-context/lib-commonjs/PortalCompatContext.js
```

## Expected Behavior
Web app should not have runtime error. Other solutions I have come across such as `npx jest --clearCache` and `npm install @babel/runtime` have not fixed the issue.

<img width="1505" alt="Screenshot 2023-09-07 at 10 38 40 PM" src="https://github.com/microsoft/fluentui/assets/5560075/a08833ac-1423-4064-ba73-2991a0ea6e85">
<img width="1505" alt="Screenshot 2023-09-07 at 10 38 40 PM" src="https://github.com/microsoft/fluentui/assets/5560075/ed755fde-1dcd-45c3-b343-f789e859fbc5">

### Logs

```shell
ERROR
_interop_require_wildcard._ is not a function
TypeError: _interop_require_wildcard._ is not a function
    at ./node_modules/@fluentui/react-portal-compat-context/lib-commonjs/PortalCompatContext.js (http://localhost:3001/static/js/bundle.js:60789:53)
    at options.factory (http://localhost:3001/static/js/bundle.js:256063:31)
    at __webpack_require__ (http://localhost:3001/static/js/bundle.js:255478:33)
    at fn (http://localhost:3001/static/js/bundle.js:255720:21)
    at ./node_modules/@fluentui/react-portal-compat-context/lib-commonjs/index.js (http://localhost:3001/static/js/bundle.js:60830:28)
    at options.factory (http://localhost:3001/static/js/bundle.js:256063:31)
    at __webpack_require__ (http://localhost:3001/static/js/bundle.js:255478:33)
    at fn (http://localhost:3001/static/js/bundle.js:255720:21)
    at ./node_modules/@fluentui/react/lib-commonjs/components/Layer/Layer.base.js (http://localhost:3001/static/js/bundle.js:99606:37)
    at options.factory (http://localhost:3001/static/js/bundle.js:256063:31)
```

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@vcpavao Can you check if you have `@swc/helpers` installed as a dependency in your codebase?

**Comment by lfsp21** [comment]
> @vcpavao Can you check if you have `@swc/helpers` version <= `0.4.35` is installed as a dependency in your codebase?

I am having the same error, I have @swc/helpers 0.4.14 version

**Comment by TristanWatanabe** [comment]
@lfsp21 Can you tell me the version of `@fluentui/react-components` that you're on? If you're on version `>=9.30.2` then you should be on `swc/helpers` version `>=0.5.2`

**Comment by lfsp21** [comment]
@TristanWatanabe I'm on version 9.19.1

**Comment by NotWoods** [comment]
We're also seeing this as a build error when we try to update to 9.31.0. We're using swc/helpers 0.5.1

**Comment by JasonGore** [comment]
I have an internal repro posted to Teams channel.
- `@fluentui/react-components` version `9.30.0`. Unchanged from working master.
- `@swc/helpers` versions `0.4.14` and `0.5.1`. Likewise unchanged from working master, however more versions of fluentui deps are using `0.5.1` with my repro, which makes me wonder if the issue is related to `0.5.1`.

**Comment by JasonGore** [comment]
Give the exact same repro state, I let `@linaria/babel-preset` resolve from `3.0.0-beta.23` to the newest version `3.0.0-beta.24` (by removing its entry in the yarn lockfile and rerunning yarn) and that alone appears to fix the griffel error.

**Comment by Zefz** [comment]
Workaround is to downgrade `react-portal-compat-context` to previous version:

`npm i @fluentui/react-portal-compat-context@9.0.6`

**Comment by vcpavao** [comment]
> @vcpavao Can you check if you have `@swc/helpers` version <= `0.4.35` is installed as a dependency in your codebase? If you do then I advise bumping to version >= `0.5.1`

The version is @swv/helpers 0.5.2

**Comment by writetosalman** [comment]
I am also facing same issue :-( 
I will watch this thread for now

**Comment by Stan-Stani** [comment]
@jeffersoneagley Yes, I don't use it either. We fixed it with @Zefz 's suggestion, but as some of our team run our main project linked to a local copy of our npm package repo there are a ton of weird type errors and microbundler does **not** like them. `yarn upgrade-interactive` and bumping all the types maybe seems to have fixed that specific issue.

**Comment by jeffersoneagley** [comment]
I've tried the above fixes, and they don't work.

**Comment by jeffersoneagley** [comment]
PortalCompatContext.js:20  Uncaught TypeError: _interop_require_wildcard._ is not a function
    at ./node_modules/@fluentui/react-portal-compat-context/lib-commonjs/PortalCompatContext.js (PortalCompatContext.js:20:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@fluentui/react-portal-compat-context/lib-commonjs/index.js (index.js:19:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@fluentui/react/lib-commonjs/components/Layer/Layer.base.js (Layer.base.tsx:3:1)
    at options.factory (react refresh:6:1)

**Comment by layershifter** [comment]
If somebody still has this issue and suggestions above don't work, please provide a repro and I will check/reopen the issue. Thx
