### ISSUE TITLE
[Bug]: In Breadcrumb, test warning 'Icon "chevronright" was used but not registered'

### ISSUE THREAD

**Issue by 15MariamS** [microsoft/fluentui#29333]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 28.17 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.5.2
```

### Are you reporting Accessibility issue?

None

### Reproduction

On an npm test run (not sure how to provide repro)

## Actual Behavior

Using `import { Breadcrumb, IBreadcrumbItem } from "@fluentui/react/lib/Breadcrumb";`. When I run `npm test`:

```
 The icon "chevronright" was used but not registered. See https://github.com/microsoft/fluentui/wiki/Using-icons for more information.
```

## Expected Behavior
No warning message on the Jest test

**Question: Is the new breadcrumb component going to be available soon?** Would love to see if this already gets solved there.

### Logs

```shell
console.warn
      The icon "chevronright" was used but not registered. See https://github.com/microsoft/fluentui/wiki/Using-icons for more information.

      at warn (node_modules/@fluentui/utilities/lib-commonjs/src/warn/warn.ts:17:13)
      at getIcon (node_modules/@fluentui/style-utilities/lib-commonjs/src/utilities/icons.ts:199:13)
      at node_modules/@fluentui/react/lib-commonjs/components/src/components/Icon/FontIcon.tsx:17:105
      at memoizedFunction (node_modules/@fluentui/utilities/src/memoize.ts:139:29)
      at IconBase.Object.<anonymous>.IconBase.render (node_modules/@fluentui/react/lib-commonjs/components/src/components/Icon/Icon.base.tsx:36:39)
      at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:19752:31)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:19698:24)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21611:16)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26085:20)
      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:46:25
      at Object.eventWrapper (node_modules/@testing-library/react/dist/pure.js:92:28)
      at Object.wrapEvent (node_modules/@testing-library/user-event/dist/cjs/event/wrapEvent.js:29:24)
      at Object.dispatchEvent (node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:47:22)
      at Object.dispatchUIEvent (node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:24:26)
      at Mouse.up (node_modules/@testing-library/user-event/dist/cjs/system/pointer/mouse.js:104:30)
      at PointerHost.release (node_modules/@testing-library/user-event/dist/cjs/system/pointer/index.js:86:28)
      at pointerAction (node_modules/@testing-library/user-event/dist/cjs/pointer/index.js:62:47)
      at Object.pointer (node_modules/@testing-library/user-event/dist/cjs/pointer/index.js:35:9)
      at Object.asyncWrapper (node_modules/@testing-library/react/dist/pure.js:73:22)
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
> Question: Is the new breadcrumb component going to be available soon? 

Hey, I'm bit confused. Based on the issue you are using fluent v8 , which is in maintenance mode and no further features are added to it. Maybe you should consider using our latest fluent v9 https://react.fluentui.dev/

**Comment by 15MariamS** [comment]
> Maybe you should consider using our latest fluent v9 https://react.fluentui.dev/

I plan to switch, but looks like the v9 [breadcrumb component](https://react.fluentui.dev/?path=/docs/preview-components-breadcrumb--default) is still in preview mode
