### ISSUE TITLE
[Bug]: OverflowItem is not working with React 18

### ISSUE THREAD

**Issue by js-chris** [microsoft/fluentui#29976]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 AMD EPYC 7542 32-Core Processor
    Memory: 2.84 GB / 16.00 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (119.0.2151.58)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/nifty-rain-kqf93z

## Actual Behavior
OverflowItem throws an error with the latest fluent-ui 9 components and React 18. Also the component "Breadcrumb" has this behavior.

## Expected Behavior
Properly working OverflowItem and Breadcrumb

### Logs

```shell
react-dom.development.js:22839 Uncaught TypeError: Cannot read properties of undefined (reading 'priority')
    at compareItems (overflowManager.js:42:1)
    at overflowManager.js:57:1
    at heapify (priorityQueue.js:25:1)
    at Object.remove (priorityQueue.js:71:1)
    at Object.removeItem (overflowManager.js:199:1)
    at useOverflowContainer.js:63:1
    at safelyCallDestroy (react-dom.development.js:22932:1)
    at commitHookEffectListUnmount (react-dom.development.js:23100:1)
    at commitMutationEffectsOnFiber (react-dom.development.js:24312:1)
    at recursivelyTraverseMutationEffects (react-dom.development.js:24273:1)
compareItems @ overflowManager.js:42
(anonymous) @ overflowManager.js:57
heapify @ priorityQueue.js:25
remove @ priorityQueue.js:71
removeItem @ overflowManager.js:199
(anonymous) @ useOverflowContainer.js:63
safelyCallDestroy @ react-dom.development.js:22932
commitHookEffectListUnmount @ react-dom.development.js:23100
commitMutationEffectsOnFiber @ react-dom.development.js:24312
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24332
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24346
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24293
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24576
recursivelyTraverseMutationEffects @ react-dom.development.js:24273
commitMutationEffectsOnFiber @ react-dom.development.js:24432
commitMutationEffects @ react-dom.development.js:24243
commitRootImpl @ react-dom.development.js:26810
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sydsutton** [comment]
I came across the same problem today when updating `@fluentui/react-components` from `9.34.1` to `9.42.0`. Thanks for opening this, @js-chris !

**Comment by sydsutton** [comment]
Also, @js-chris , this is just based on observation from the many updates I've done recently, but I have a feeling this is a bug that was introduced somewhere between `v9.34.1` and `v9.42.0` and doesn't necessarily have to do with React 18. But I definitely could be wrong.

**Comment by js-chris** [comment]
Hi @sydsutton good to know that someone else has this problem too. Of course I am not 100% sure that is is only related to React 18. I came across this, because all examples in the fluent ui 9 documentation run with React 17 and if I run my example from above with React 17, it works as well.

**Comment by kamilkazmierczakMtab** [comment]
As a temporary workaround you can add this to `package.json`
```
  "overrides": {
    "@fluentui/react-components": {
      "@fluentui/react-overflow": "9.1.0"
    }
  },
  ```

**Comment by burgua** [comment]
@js-chris thx for opening this. Had a lot of troubles with overflow items that use this package sind few weeks. Maybe with enough attention to the topic we got that fixed 🤌

**Comment by htryggva** [comment]
I'm also seeing problems with overflow items in toolbars with @fluentui/react-components 9.43.0 and @fluentui/react-overflow 9.1.2. The temp workaround from @kamilkazmierczakMtab works for me for now but I would also love to see support for StrictMode restored :)

**Comment by buzzo123** [comment]
I added the overrides to the `package.json`, deleted the `yarn.lock` and the fluetui folder in node_modules but it continue to install the 9.1.4 i don't know why

**Comment by sydsutton** [comment]
@buzzo123 I would try unistalling `react-components`, adding the overrides to the package.json, then re-installing `react-components`. That worked for me at least.

**Comment by js-chris** [comment]
Hi @buzzo123, because I am using pnpm I needed in my package.json, maybe this helps:

`   
     "pnpm": {
        "overrides": {
            "@fluentui/react-overflow": "9.1.0"
        }
    },
`

**Comment by sydsutton** [comment]
Hi @spmonahan , is there any way you would be able to add some labels to this for more visibility? This bug would be 100% blocking if it weren't for @kamilkazmierczakMtab 's temporary workaround. Thanks!

**Comment by marcosmoura** [comment]
This issue has been fixed. Please note that it won't be available as soon as it gets merged, but it will be shipped on the next release.

**Comment by sydsutton** [comment]
Thank you, @marcosmoura!
