### ISSUE TITLE
[Bug]: Failed to render MessageBar component in tests

### ISSUE THREAD

**Issue by rosergeev** [microsoft/fluentui#30077]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
    Memory: 2.74 GB / 16.00 GB
  Browsers:
    Edge: Chromium (118.0.2088.76)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/devbox/romantic-wiles-z3tvdl

## Actual Behavior

I created a simple wrapper of MessageBar component and wrote a snapshot test where I just try to render it. Render function fails with following error:
TypeError: win.ResizeObserver is not a constructor

Actually, in our production code I've started the replacement of the old Alert component with the new MessageBar component. And a bunch of tests are failed.

## Expected Behavior

render function shouldn't fail with MessageBar component

### Logs

```shell
Here it is the stacktrace:
at node_modules/@fluentui/react-message-bar/lib-commonjs/components/MessageBar/useMessageBarReflow.js:71:32
      at node_modules/@fluentui/react-utilities/lib-commonjs/hooks/useMergedRefs.js:19:17
      at commitAttachRef (node_modules/react-dom/cjs/react-dom.development.js:23650:18)
      at commitLayoutEffectOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23503:9)
      at commitLayoutMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24674:7)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:24612:3)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26823:5)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at finishConcurrentRender (node_modules/react-dom/cjs/react-dom.development.js:25981:9)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25809:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:46:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:161:26)
      at render (node_modules/@testing-library/react/dist/pure.js:247:10)
      at Object.<anonymous> (src/MessageWrapper.test.tsx:7:29)
```

### Requested priority

Blocking

### Products/sites affected

ImageMaster

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Is it possible to create a reduced demo. This is a large complex application and the issue could be coming from a number of sources.

**Comment by rosergeev** [comment]
It's a minimal application with one component and one test for this component. Just create new terminal and run 'npm run test'

**Comment by rosergeev** [comment]
Or you can recreate it locally, just create a component with MessageBar and write a test that renders it

**Comment by rosergeev** [comment]
I have created a new minimal reproduction:
https://codesandbox.io/p/sandbox/messagebarintests-tnv64p

output of test results is the following:

> vitest run --environment jsdom


 RUN  v1.2.2 /workspaces/workspace

stderr | src/tests/MessageBarWrapper.test.tsx > MessageBar tests > Snapshot test should not regress
Error: Uncaught [TypeError: win.ResizeObserver is not a constructor]
    at reportException (/workspaces/workspace/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at innerInvokeEventListeners (/workspaces/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
    at invokeEventListeners (/workspaces/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLUnknownElementImpl._dispatch (/workspaces/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLUnknownElementImpl.dispatchEvent (/workspaces/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
    at HTMLUnknownElement.dispatchEvent (/workspaces/workspace/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
    at Object.invokeGuardedCallbackDev (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
    at invokeGuardedCallback (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
    at reportUncaughtErrorInDEV (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:22838:5)
    at captureCommitPhaseError (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:27126:5) TypeError: win.ResizeObserver is not a constructor
    at /workspaces/workspace/node_modules/@fluentui/react-message-bar/lib-commonjs/components/MessageBar/useMessageBarReflow.js:71:32
    at /workspaces/workspace/node_modules/@fluentui/react-utilities/lib-commonjs/hooks/useMergedRefs.js:19:17
    at commitAttachRef (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:23650:18)
    at commitLayoutEffectOnFiber (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:23503:9)
    at commitLayoutMountEffects_complete (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:24688:9)
    at commitLayoutEffects_begin (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:24674:7)
    at commitLayoutEffects (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:24612:3)
    at commitRootImpl (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:26823:5)
    at commitRoot (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:26682:5)
    at finishConcurrentRender (/workspaces/workspace/node_modules/react-dom/cjs/react-dom.development.js:25981:9)
The above error occurred in the <div> component:

    at div
    at /workspaces/workspace/node_modules/@fluentui/react-message-bar/lib-commonjs/components/MessageBar/MessageBar.js:19:61
    at div
    at MessageBarWrapper

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

 ❯ src/tests/MessageBarWrapper.test.tsx (1)
   ❯ MessageBar tests (1)
     × Snapshot test should not regress

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/tests/MessageBarWrapper.test.tsx > MessageBar tests > Snapshot test should not regress
TypeError: win.ResizeObserver is not a constructor
 ❯ node_modules/@fluentui/react-message-bar/lib-commonjs/components/MessageBar/useMessageBarReflow.js:71:32
 ❯ node_modules/@fluentui/react-utilities/lib-commonjs/hooks/useMergedRefs.js:19:17
 ❯ commitAttachRef node_modules/react-dom/cjs/react-dom.development.js:23650:18
 ❯ commitLayoutEffectOnFiber node_modules/react-dom/cjs/react-dom.development.js:23503:9
 ❯ commitLayoutMountEffects_complete node_modules/react-dom/cjs/react-dom.development.js:24688:9
 ❯ commitLayoutEffects_begin node_modules/react-dom/cjs/react-dom.development.js:24674:7
 ❯ commitLayoutEffects node_modules/react-dom/cjs/react-dom.development.js:24612:3
 ❯ commitRootImpl node_modules/react-dom/cjs/react-dom.development.js:26823:5
 ❯ commitRoot node_modules/react-dom/cjs/react-dom.development.js:26682:5
 ❯ finishConcurrentRender node_modules/react-dom/cjs/react-dom.development.js:25981:9

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  1 failed (1)
   Start at  14:47:38
   Duration  2.49s (transform 54ms, setup 0ms, collect 1.64s, tests 62ms, environment 510ms, prepare 77ms)

**Comment by sopranopillow** [comment]
Hi @rosergeev, will look into it as soon as I get a chance. Thanks for the codesandbox :)

**Comment by rosergeev** [comment]
@sopranopillow, muchas gracias!

**Comment by sopranopillow** [comment]
Hi @rosergeev, with the new update to codesandbox, I can't access the codesandbox. By any chance could you move it to stackblitz or make sure it's not a draft and visibility is set to public? thanks!

**Comment by rosergeev** [comment]
> Hi @rosergeev, with the new update to codesandbox, I can't access the codesandbox. By any chance could you move it to stackblitz or make sure it's not a draft and visibility is set to public? thanks!

Yes, it was private - I have changed to public
https://codesandbox.io/p/devbox/romantic-wiles-z3tvdl?file=%2Fsrc%2FMessageWrapper.tsx

**Comment by sopranopillow** [comment]
Looked into this, it looks like you are missing mocking the ResizeObserver. As you can see from the stack trace, you are trying to access window.ResizeObserver which is not available. Jest lets you have js-dom, but it doesn't mock the observers for you. This is how you can get around it:
```tsx
import * as React from "react";
import { render } from "@testing-library/react";
import { MessageWrapper } from "./MessageWrapper";

let origResizeObserver: typeof global.ResizeObserver;

describe("The MessageWrapper component", () => {
  beforeAll(() => {
    origResizeObserver = global.ResizeObserver;
    global.ResizeObserver = jest.fn().mockImplementation(() => ({
      observe: jest.fn(),
      unobserve: jest.fn(),
      disconnect: jest.fn(),
    }));
  });
  test("Snapshot test", () => {
    const container = render(<MessageWrapper />);
    expect(container).toMatchSnapshot();
  });
});
```

I've tested it locally and it works. I'm closing the issue since this is not a fix on our side, but feel free to ask more questions or reopen if needed. Sorry for taking long to answer and thank you for your patience :)
