### ISSUE TITLE
[Feature]: Add `.js` file extension to built output to improve native ESM support

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#30634]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

I want Fluent's ESM output (CJS can go either way I think) to include the `.js` extension for all relative JS imports. For example,

```js
// Source Typescript
import { feature } from './file';

// Output ESM Javascript
import { feature } from './file.js';
```
This update will better allow Fluent's ESM output to be loaded directly in the browser ([import maps](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) will still be required to resolve bare package imports but that's no problem).

Ideally we should do this without changing source code and leverage something like SWC's `@swc/plugin-transform-imports` (which transforms exports in addition to imports despite the name).

### Have you discussed this feature with our team

@hotell @chrisdholt

### Additional context

Currently the ESM output from Fluent is "extensionless" which prevents the ESM output from working correctly in a browser.

```js
// Example output of current output
import { FluentProvider } from '@fluentui/react-components'; // bare module
export { something } from './somewhere'; // bare JS file

// Example of what this needs to be for native ESM support
import { FluentProvider { from '@fluentui/react-components;
export { something } from './somewhere.js';
```

In this example there is a "bare module" import where code is imported from a package name (that lacks a `.js` extension) and a "bare JS file" import. The latter is typically used within a package to import other JS files using relative paths.

We can address "bare modules" with [importmaps](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap), allowing `import $whatever from 'some-module-without-an-extension'` to resolve correctly but importmaps cannot, effectively<sup>†</sup>, handle the internal bare JS imports. To handle the bare JS imports we must update the output to include the `.js` extension.

<sup>†</sup> I say _effectively_ because it is possible to generate an importmap for all the base JS imports within a package but such an importmap would be quite large and then require end users to correctly merge it with any other importmaps they are using. Technically possible but not a good solution :)

## Related issues

- #23508

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by Hotell** [comment]
@miroslavstastny  I'm re-assigning this to v-build as we will be shipping it

**Comment by Hotell** [comment]
to clarify few things

- just adding the extensions won't do "anything"
- the package itself needs to ship an actual native ESM output. For that we have 2 options:
 
1. declaring package as ESM native via `type:module` pragma

- use `.js` extension within imports within package scope

2. shipping all ESM files having `.mjs` extension

By default in ESM native environments, if a package.json has no `type` specified it fallbacks to `type:commonjs` by default (our packages situation).

While we have export maps in place, they are invalid for native ESM loader ( it works solely for build tools with current output )

In order to support native ESM loader without making the package native ESM, all files that are accessed via `exports#import` need to:
- have `.mjs` extension
- use `.js` extension within imports within package scope

**Comment by spmonahan** [comment]
Re-opening since we had to revert this in #30803

**Comment by yuntian001** [comment]
I need it. When do you plan to fix it

**Comment by AnujAgrawal-1** [comment]
Any update on above issue as i am also getting same issue
`  SyntaxError: Unexpected token 'export'
      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/@fluentui/react-provider/lib-commonjs/components/FluentProvider/renderFluentProvider.js:15:20)`
