### ISSUE TITLE
[Bug]: Tooltip jest test regression after react 18 fix if `autoMount` set to true

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/fluentui#30896]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
`sh: 1: envinfo: not found`


    "@fluentui/react-components": "^9.47.2",
    "@fluentui/react": "^8.117.0",
    "@fluentui/react-file-type-icons": "8.11.5",
    "@fluentui/react-hooks": "^8.7.0",
    "@fluentui/react-icons": "^2.0.233",
    "@fluentui/react-window-provider": "^2.2.18",
    "@fluentui-contrib/react-chat": "0.1.9",
```

### Are you reporting Accessibility issue?

None

### Reproduction

not available in codepen

### Bug Description

After https://github.com/microsoft/fluentui/pull/28232 jest complains:
```
Warning: Attempted to synchronously unmount a root while React was already rendering. React cannot finish unmounting the root until the current render has completed, which may lead to a race condition.
      at BaseButton (../../../common/temp/node_modules/.pnpm/@fluentui+react@8.117.0_@types+react-dom@18.2.21_@types+react@18.2.64_react-dom@18.2.0_react@18.2.0/node_modules/@fluentui/react/lib-commonjs/components/src/components/Button/BaseButton.tsx:99:5)
      at DefaultButton (../../../common/temp/node_modules/.pnpm/@fluentui+react@8.117.0_@types+react-dom@18.2.21_@types+react@18.2.64_react-dom@18.2.0_react@18.2.0/node_modules/@fluentui/react/lib-commonjs/components/Button/DefaultButton/DefaultButton.js:15:42)
      at ComponentWithInjectedProps (../../../common/temp/node_modules/.pnpm/@fluentui+utilities@8.15.0_@types+react@18.2.64_react@18.2.0/node_modules/@fluentui/utilities/lib-commonjs/src/customizations/customizable.tsx:23:9)
          at div
      at ResultComponent (../../../common/temp/node_modules/.pnpm/@fluentui+foundation-legacy@8.4.0_@types+react@18.2.64_react@18.2.0/node_modules/@fluentui/foundation-legacy/src/createComponent.tsx:55:13)
          at div
      at TooltipHostBase (../../../common/temp/node_modules/.pnpm/@fluentui+react@8.117.0_@types+react-dom@18.2.21_@types+react@18.2.64_react-dom@18.2.0_react@18.2.0/node_modules/@fluentui/react/lib-commonjs/components/src/components/Tooltip/TooltipHost.base.tsx:50:5)
      at ../../../common/temp/node_modules/.pnpm/@fluentui+utilities@8.15.0_@types+react@18.2.64_react@18.2.0/node_modules/@fluentui/utilities/src/styled.tsx:95:26
````

### Requested priority

Low

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@JamesBurnside Can you provide an example test so any fix can be validated? I thinking a new test in the `Tooltip` test suite.
