### ISSUE TITLE
[Bug]: Dialog fails to render if DialogSurface is in another component

### ISSUE THREAD

**Issue by romangobrey** [microsoft/fluentui#31630]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.24 GB / 15.91 GB
Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://github.com/romangobrey/fluent-dialog-bug

## General Info
Default example is taken from - https://react.fluentui.dev/?path=/docs/components-dialog--default
If a Dialog (parent) component and all child components (e.g. DialogSurface component) is in the same/one component than it works. If a DialogSurface component is extracted to a separate component (e.g. based on some condition user wants to render different dialog content) render fails.

The only version I was able to identify that supports this spitting is @fluentui/react-components 9.47.5

## Actual Behavior
1. Clone the repo
2. npm run start
3. See error in dev tools - 
Error: @fluentui/react-motion: Invalid child element.
Motion factories require a single child element to be passed. That element element should support ref forwarding i.e. it should be either an intrinsic element (e.g. div) or a component that uses React.forwardRef().

## Expected Behavior
Component is rendered

### Logs

```shell
Error: @fluentui/react-motion: Invalid child element.
Motion factories require a single child element to be passed. That element element should support ref forwarding i.e. it should be either an intrinsic element (e.g. div) or a component that uses React.forwardRef().
    at getChildElement (getChildElement.js:12:1)
    at Presence (createPresenceComponent.js:20:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at mountIndeterminateComponent (react-dom.development.js:20103:1)
    at beginWork (react-dom.development.js:21626:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27490:1)
    at performUnitOfWork (react-dom.development.js:26596:1)

Error: @fluentui/react-motion: Invalid child element.
Motion factories require a single child element to be passed. That element element should support ref forwarding i.e. it should be either an intrinsic element (e.g. div) or a component that uses React.forwardRef().
    at getChildElement (getChildElement.js:12:1)
    at Presence (createPresenceComponent.js:20:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at mountIndeterminateComponent (react-dom.development.js:20103:1)
    at beginWork (react-dom.development.js:21626:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27490:1)
    at performUnitOfWork (react-dom.development.js:26596:1)

The above error occurred in the <Presence> component:

    at Presence (http://localhost:3000/static/js/bundle.js:6633:60)
    at Provider (http://localhost:3000/static/js/bundle.js:3448:70)
    at http://localhost:3000/static/js/bundle.js:3025:79
    at DefaultDialog
    at div
    at App
    at div
    at TextDirectionProvider (http://localhost:3000/static/js/bundle.js:13201:3)
    at http://localhost:3000/static/js/bundle.js:7330:95

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

Error: @fluentui/react-motion: Invalid child element.
Motion factories require a single child element to be passed. That element element should support ref forwarding i.e. it should be either an intrinsic element (e.g. div) or a component that uses React.forwardRef().
    at getChildElement (getChildElement.js:12:1)
    at Presence (createPresenceComponent.js:20:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at mountIndeterminateComponent (react-dom.development.js:20103:1)
    at beginWork (react-dom.development.js:21626:1)
    at beginWork$1 (react-dom.development.js:27465:1)
    at performUnitOfWork (react-dom.development.js:26596:1)
    at workLoopSync (react-dom.development.js:26505:1)
    at renderRootSync (react-dom.development.js:26473:1)
    at recoverFromConcurrentError (react-dom.development.js:25889:1)
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@romangobrey 

<img width="740" alt="image" src="https://github.com/microsoft/fluentui/assets/14183168/ae7c1347-2faa-422e-a6da-7a5726d51a57">

I would say the error is self-descriptive 🐱 `DefaultDialogSurface` should use `React.forwardRef()` i.e.:

```tsx
const DefaultDialogSurface = React.forwardRef((props, ref) => {
  return <DialogSurface ref={ref} />
})
```

**Comment by romangobrey** [comment]
Ok, my bad 🙈
Thank you for clarifying!
