### ISSUE TITLE
[Bug]: `yarn create-package`  doesn't work on Windows

### ISSUE THREAD

**Issue by ValentinaKozlova** [microsoft/fluentui#31987]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 16.44 GB / 31.60 GB
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

no

### Reproduction

vbuild

## Steps:
1. Pull from master and run `yarn` from `fluentui` folder.
2. Run `yarn create-package [package-name]` and follow instruction.

## Actual Behavior
It's only on Windows. There's an error "Cannot find packages ...."
![image](https://github.com/user-attachments/assets/44de17d0-50dc-4fd7-838e-34d8935c5f93)

## Expected Behavior
Component should be created.

## Notes
This is caused by 
line 144, 145:
```ts
makeSrcLibrary(tree, normalizedOptions, logger);
makeStoriesLibrary(tree, normalizedOptions, logger);
```
It'll work if we change order:
```ts
makeStoriesLibrary(tree, normalizedOptions, logger);
makeSrcLibrary(tree, normalizedOptions, logger);
```

### Logs

```shell
NX   Cannot find packages/react-components/test-component-preview/stories/.storybook/tsconfig.json


Error: Cannot find packages/react-components/test-component-preview/stories/.storybook/tsconfig.json
    at readJson (C:\Repos\test\fluentui\node_modules\nx\src\generators\utils\json.js:14:15)
    at updateJson (C:\Repos\test\fluentui\node_modules\nx\src\generators\utils\json.js:46:34)
    at makeStoriesLibrary (C:\Repos\test\fluentui\tools\workspace-plugin\src\generators\split-library-in-two\generator.ts:392:13)
    at splitLibraryInTwoInternal (C:\Repos\test\fluentui\tools\workspace-plugin\src\generators\split-library-in-two\generator.ts:145:3)
    at splitLibraryInTwoGenerator (C:\Repos\test\fluentui\tools\workspace-plugin\src\generators\split-library-in-two\generator.ts:90:5)
    at default_1 (C:\Repos\test\fluentui\tools\workspace-plugin\src\generators\react-library\index.ts:38:35)
    at async C:\Repos\test\fluentui\node_modules\nx\src\command-line\generate\generate.js:241:26
    at async handleErrors (C:\Repos\test\fluentui\node_modules\nx\src\utils\params.js:9:24)
    at async Object.handler (C:\Repos\test\fluentui\node_modules\nx\src\command-line\generate\command-object.js:13:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Hotell** [comment]
verified that this issue is happening only on windows native shells (powershell, cmd.exe )
