### ISSUE TITLE
[Bug]: Telemetry showing TypeError: i.persist is not a function

### ISSUE THREAD

**Issue by samuelec** [microsoft/fluentui#33010]
### Package

react

### Package version

"@fluentui/react": "^8.118.8",

### React version

18.2.0

### Environment

```shell
This command does not work properly against our configuration.

        "@fluentui-contrib/react-data-grid-react-window": "^1.1.2",
        "@fluentui-contrib/react-headless-provider": "^1.0.1",
        "@fluentui-copilot/react-copilot-chat": "^0.7.6",
        "@fluentui-copilot/react-sensitivity-label": "^0.5.0",
        "@fluentui-copilot/react-suggestions": "^0.8.3",
        "@fluentui/date-time-utilities": "^8.4.0",
        "@fluentui/example-data": "^8.4.0",
        "@fluentui/font-icons-mdl2": "^8.1.6",
        "@fluentui/keyboard-keys": "^9.0.7",
        "@fluentui/merge-styles": "^8.4.0",
        "@fluentui/react": "^8.118.8",
        "@fluentui/react-brand-icons": "^1.0.133",
        "@fluentui/react-button": "^9.1.6",
        "@fluentui/react-calendar-compat": "^0.1.12",
        "@fluentui/react-card": "9.0.0-beta.34",
        "@fluentui/react-charting": "^5.17.1",
        "@fluentui/react-components": "^9.51.1",
        "@fluentui/react-datepicker-compat": "^0.4.42",
        "@fluentui/react-file-type-icons": "^8.6.0",
        "@fluentui/react-hooks": "^8.5.0",
        "@fluentui/react-icons": "^2.0.252",
        "@fluentui/react-link": "^9.1.10",
        "@fluentui/react-overflow": "^9.0.0-rc.2",
        "@fluentui/react-portal-compat": "^9.0.100",
        "@fluentui/react-positioning": "^9.9.21",
        "@fluentui/react-provider": "^9.1.5",
        "@fluentui/react-search": "^9.0.6",
        "@fluentui/react-shared-contexts": "^9.1.1",
        "@fluentui/react-tabster": "^9.14.6",
        "@fluentui/react-text": "9.1.8",
        "@fluentui/react-theme": "^9.1.1",
        "@fluentui/react-theme-sass": "^9.0.0-alpha.20",
        "@fluentui/react-timepicker-compat": "^0.2.20",
        "@fluentui/react-utilities": "^9.1.2",
        "@fluentui/react-window-provider": "^2.1.0",
        "@fluentui/style-utilities": "^8.6.0",
        "@fluentui/theme": "^2.4.11",
        "@fluentui/utilities": "^8.13.19",

        "react": "^18.2.0",
        "react-csv": "^2.0.3",
        "react-dom": "^18.2.0",
        "react-horizontal-scrolling-menu": "0.7.10",
        "react-infinite-scroll-component": "^5.1.0",
        "react-inspector": "^2.2.2",
        "react-redux": "^7.1.0",
        "react-relay": "^14.1.0",
        "react-router": "^6.22.3",
        "react-router-dom": "^6.22.3",
        "react-transition-group": "^4.2.1",
        "react-virtualized-auto-sizer": "^1.0.6",
        "react-vtree": "^2.0.4",
        "react-webcam": "^7.1.1",
        "react-window": "^1.8.7",
```

### Current Behavior

The application is hitting this

Callstack:
TypeError: i.persist is not a function at https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:40440 at Array.map () at https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:40342 at https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:41839 at az (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:895966) at aJ (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:902346) at e (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:922944) at https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:922955 at sz (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:923467) at sF (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:908095) at n6 (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:856780) at sI (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.61781.m.26b036fb.js:31:908208) at tE (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.mailindex.35921ee6.js:2:144617) at tx (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.mailindex.35921ee6.js:2:141486) at ty (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.mailindex.35921ee6.js:2:138557) at nm (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.mailindex.35921ee6.js:2:148497) at s (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.mailindex.35921ee6.js:2:176037) at a (https://res.public.onecdn.static.microsoft/owamail/hashed-v1/scripts/owa.mailindex.35921ee6.js:2:175462) at https://res.public.onecdn.static.mic

Original Callstack:
webpack://owa/node_modules/@fluentui/react-motion/lib/hooks/useAnimateAtoms.js 17
' '
webpack://owa/node_modules/@fluentui/react-motion/lib/hooks/useAnimateAtoms.js 8
webpack://owa/node_modules/@fluentui/react-motion/lib/factories/createPresenceComponent.js 84
webpack://owa/node_modules/react-dom/cjs/react-dom.production.min.js 244
webpack://owa/node_modules/react-dom/cjs/react-dom.production.min.js 261
webpack://owa/node_modules/react-dom/cjs/react-dom.production.min.js 260
webpack://owa/node_modules/react-dom/cjs/react-dom.production.min.js 259
webpack://owa/node_modules/react-dom/cjs/react-dom.production.min.js 281
webpack://owa/node_modules/react-dom/cjs/react-dom.production.min.js 273
webpack://owa/node_modules/react-dom/cjs/react-dom.production.min.js 127
webpack://owa/node_modules/react-dom/cjs/react-dom.production.min.js 274
webpack://owa/node_modules/mobx/src/core/reaction.ts 275
webpack://owa/node_modules/mobx/src/core/reaction.ts 242
webpack://owa/node_modules/mobx/src/core/observable.ts 112
webpack://owa/node_modules/mobx/src/api/transaction.ts 15
webpack://owa/node_modules/satcheljs/lib-esm/dispatcher.js 17
webpack://owa/node_modules/satcheljs/lib-esm/actionCreator.js 23__

### Expected Behavior

No exception is thrown

### Reproduction

https://aka.ms/fluentpen

### Steps to reproduce

Only detected by telemetry.

### Are you reporting an Accessibility issue?

None

### Suggested severity

Medium - Has workaround

### Products/sites affected

Outlook

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Can you correlate the issue with a browser?

[According to MDN this feature](https://developer.mozilla.org/en-US/docs/Web/API/Animation#browser_compatibility) is within our [browser support](https://react.fluentui.dev/?path=/docs/concepts-developer-browser-support-matrix--docs#full-browser-support-matrix).

**Comment by spmonahan** [comment]
@tudorpopams, as we discussed offline assigning this to you.

This feature is in the gray area between our full and partial support matrixes so we'll update our docs to call out the need to polyfill this feature for partial support.

A polyfill exists, though I have not vetted it: https://github.com/web-animations/web-animations-js

**Comment by tudorpopams** [comment]
Has the polyfill provided by @spmonahan solved this issue? Can we close it?
