### ISSUE TITLE
[Bug]: Latest version do not have lib directory

### ISSUE THREAD

**Issue by rgcircum** [microsoft/fluentui#33265]
### Package

react

### Package version

8.121.10

### React version

17

### Environment

```shell
Windows
```

### Current Behavior

Latest version do not have lib directory. it crashes on build.

8.121.10

![Image](https://github.com/user-attachments/assets/16877974-0251-42fb-9566-34da4e81cec2)
https://www.npmjs.com/package/@fluentui/react?activeTab=code

8.121.9
![Image](https://github.com/user-attachments/assets/69e62aae-1abe-4fb4-a5de-a4783f9a42a0)
https://www.npmjs.com/package/@fluentui/react/v/8.121.9?activeTab=code

Package @fluentui/fluent2-theme have the same problem, this makes all version of @fluentui/react-migration-v8-v9 unusable

https://www.npmjs.com/package/@fluentui/fluent2-theme/v/8.107.113?activeTab=code

### Expected Behavior

to be corrected quickly

### Reproduction

update this lib to latest version, install and build it.

### Steps to reproduce

update this lib to latest version, install and build it.

### Are you reporting an Accessibility issue?

None

### Suggested severity

Urgent - No workaround and Products/sites are affected

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by rcbevans** [comment]
Just bumped @fluentui/react and seeing total build failure with vite, I assume same issue

> error during build:
[commonjs--resolver] Failed to resolve entry for package "@fluentui/react". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///src/project/packages/client/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46637:15)
    at resolvePackageEntry (file:///src/project/packages/client/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46634:3)
    at tryNodeResolve (file:///src/project/packages/client/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46450:16)
    at Object.resolveId (file:///src/project/packages/client/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46200:19)
    at file:///src/project/packages/client/node_modules/rollup/dist/es/shared/node-entry.js:20730:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///src/project/packages/client/node_modules/rollup/dist/es/shared/node-entry.js:20630:28)
    at async resolveId (file:///src/project/packages/client/node_modules/rollup/dist/es/shared/node-entry.js:19234:26)
    at async ModuleLoader.resolveId (file:///src/project/packages/client/node_modules/rollup/dist/es/shared/node-entry.js:19663:15)
    at async Object.resolveId (file:///src/project/packages/client/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:12833:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///src/project/packages/client/node_modules/rollup/dist/es/shared/node-entry.js:20630:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:mf" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by noahmpauls** [comment]
Also getting a total build failure after upgrading to 8.121.10, for what appears to be the same reasons.

**Comment by khmakoto** [comment]
Hello! We have deprecated version `8.121.10` from npm, if you try to install again you should be getting version `8.121.9` now.

I'm currently working on publishing a new version and will reply here accordingly when that is ready.

**Comment by khmakoto** [comment]
Version `8.121.11` has been released now, and should have all assets!
